/**
 * Name data for different nations
 */

export const NAME_DATA = {
  "roman-greek": {
    male: [
      "Marcus Aurelius", "Gaius Julius", "Lucius Maximus", "Titus Flavius", "Quintus Valerius",
      "Antonius Magnus", "Cassius Brutus", "Decimus Scipio", "Fabius Cato", "Gnaeus Pompey",
      "Hadrian Severus", "Justinian Rex", "Konstantin Basileus", "Leonidas Strategos", "Maxentius Victor",
      "Nikephoros Komnenos", "Octavius Caesar", "Publius Crassus", "Romulus Augustus", "Septimus Aurelius",
      "Theodosius Magnus", "Ulpius Trajan", "Vespasian Domitian", "Xenophon Palaiologos", "Zeno Basilikos",
      "Alexios Angelos", "Basil Porphyrogennetos", "Constantine Doukas", "Demetrios Kantakouzenos", "Emmanuel Komnenos",
      "Flavius Belisarius", "Georgios Maniakes", "Heraclius Exarch", "Ioannes Kantakouzenos", "Julius Nepos",
      "Kallinikos Argyros", "Leontios Makrembolites", "Michael Tzykandyles", "Nikias Gregoras", "Orestes Patricius",
      "Photios Chrysokokkes", "Romanos Diogenes", "Stephanos Kantakouzenos", "Theodoros Laskaris", "Urbicius Strategios",
      "Valentinian Augustus", "Zacharias Scholastikos", "Anastasios Dikoros", "Bardas Phokas", "Christophoros Mitylenaios",
      "Dionysios Areopagites", "Epiphanios Hagiopolites", "Philotheos Kokkinos", "Gregorios Palamas", "Hypatios Ephesios",
      "Ignatios Diakonos", "Kosmas Vestitor", "Laurentios Presbyter", "Methodios Patriarch", "Nektarios Kephalas",
      "Olympios Diakonos", "Prokopios Caesariensis", "Sabas Hagiorites", "Tarasios Patriarch", "Vikentios Damodes"
    ],
    female: [
      "Julia Augusta", "Livia Drusilla", "Claudia Octavia", "Valeria Messalina", "Agrippina Major",
      "Faustina Augusta", "Helena Flavia", "Theodora Basilissa", "Irene Komnenos", "Zoe Porphyrogenita",
      "Anna Dalassenos", "Eudokia Makrembolitissa", "Maria Paleologina", "Sophia Kantakouzenos", "Euphrosyne Doukaina",
      "Bertha Sulzbach", "Catherine Komnenos", "Demetria Tornikes", "Eirene Laskaris", "Gregoria Palaiologina",
      "Hypomone Kantakouzenos", "Ioanna Paleologina", "Kale Pakouriane", "Lydia Xiphilinos", "Martha Komnenos",
      "Nikephoritsa Bryennios", "Olympias Argyros", "Pulcheria Theophylaktos", "Romyla Skleros", "Styliane Zaoutzes",
      "Theoktiste Mammas", "Urania Palaiologina", "Violante Montferrat", "Xene Kantakouzenos", "Yolanda Courtenay",
      "Zenobia Kantakouzenos", "Anastasia Argyros", "Barbara Komnenos", "Chryse Laskaris", "Despoina Paleologina",
      "Eudoxia Komnenos", "Febronia Hagiorites", "Gregoria Kantakouzenos", "Helena Dragases", "Ioanna Komnenos",
      "Kalomaria Paleologina", "Lydia Kantakouzenos", "Maria Komnenos", "Nikephoritsa Paleologina", "Olympia Argyros",
      "Pelagia Kantakouzenos", "Romyla Komnenos", "Styliane Paleologina", "Theodora Komnenos", "Urania Kantakouzenos",
      "Violante Paleologina", "Xanthippe Argyros", "Yolanda Komnenos", "Zenobia Paleologina", "Anastasia Kantakouzenos"
    ]
  },

  "al-haz": {
    male: [
      "Abdul Rahman", "Ahmad ibn Saud", "Ali ibn Rashid", "Bandar al-Thani", "Fahd al-Sabah",
      "Hamad ibn Khalifa", "Ibrahim al-Rashid", "Khalid ibn Abdul", "Mansour al-Nahyan", "Nasser ibn Saud",
      "Omar al-Maktoum", "Qasim ibn Thani", "Rashid al-Sabah", "Salman ibn Abdul", "Turki al-Faisal",
      "Umar ibn Rashid", "Waleed al-Thani", "Yusuf al-Sabah", "Zayed al-Nahyan", "Abdullah ibn Saud",
      "Badr al-Rashid", "Faisal ibn Abdul", "Hamza al-Thani", "Jamal al-Sabah", "Khalil al-Nahyan",
      "Majid al-Maktoum", "Naif ibn Saud", "Osama al-Rashid", "Qais al-Thani", "Saad al-Sabah",
      "Talal ibn Abdul", "Usama al-Nahyan", "Walid al-Maktoum", "Yahya al-Rashid", "Zaid ibn Saud",
      "Adel al-Thani", "Bassam al-Sabah", "Fares al-Nahyan", "Hasan al-Maktoum", "Jarir al-Rashid",
      "Kamal ibn Saud", "Mazen al-Thani", "Nabil al-Sabah", "Othman al-Nahyan", "Qusay al-Maktoum",
      "Sami al-Rashid", "Tariq ibn Saud", "Uday al-Thani", "Wael al-Sabah", "Yasir al-Nahyan",
      "Ziyad al-Maktoum", "Amjad al-Rashid", "Bilal ibn Saud", "Fadi al-Thani", "Hazem al-Sabah",
      "Imad al-Nahyan", "Jihad al-Maktoum", "Karam al-Rashid", "Marwan ibn Saud", "Nizar al-Thani"
    ],
    female: [
      "Aisha bint Saud", "Fatima al-Rashid", "Khadija al-Thani", "Maryam al-Sabah", "Nora al-Nahyan",
      "Rania al-Maktoum", "Salma bint Abdul", "Zahra al-Rashid", "Amina al-Thani", "Basma al-Sabah",
      "Dina al-Nahyan", "Farah al-Maktoum", "Hala bint Saud", "Iman al-Rashid", "Layla al-Thani",
      "Mona al-Sabah", "Nadia al-Nahyan", "Reem al-Maktoum", "Sahar bint Abdul", "Widad al-Rashid",
      "Yasmin al-Thani", "Zeinab al-Sabah", "Abeer al-Nahyan", "Bushra al-Maktoum", "Dalal bint Saud",
      "Fawzia al-Rashid", "Ghada al-Thani", "Hayat al-Sabah", "Inaam al-Nahyan", "Jihan al-Maktoum",
      "Kawther bint Abdul", "Lubna al-Rashid", "Manal al-Thani", "Nawal al-Sabah", "Randa al-Nahyan",
      "Suha al-Maktoum", "Thuraya bint Saud", "Wafa al-Rashid", "Yara al-Thani", "Zara al-Sabah",
      "Asma al-Nahyan", "Buthaina al-Maktoum", "Dalia bint Abdul", "Fadia al-Rashid", "Ghaida al-Thani",
      "Hanan al-Sabah", "Israa al-Nahyan", "Jumana al-Maktoum", "Kholoud bint Saud", "Lina al-Rashid",
      "Maha al-Thani", "Najla al-Sabah", "Rawan al-Nahyan", "Sawsan al-Maktoum", "Taghreed bint Abdul",
      "Wejdan al-Rashid", "Yasmina al-Thani", "Zulaikha al-Sabah", "Areej al-Nahyan", "Budour al-Maktoum"
    ]
  },

  "al-wazif": {
    male: [
      "Ahmed Pasha", "Mehmet Bey", "Osman Efendi", "Mustafa Aga", "Ibrahim Pasha",
      "Selim Bey", "Yusuf Efendi", "Hasan Aga", "Kemal Pasha", "Ismail Bey",
      "Mahmud Efendi", "Suleiman Aga", "Rashid Pasha", "Farid Bey", "Nasser Efendi",
      "Khalil Aga", "Tariq Pasha", "Jamal Bey", "Samir Efendi", "Adel Aga",
      "Fouad Pasha", "Karim Bey", "Marwan Efendi", "Nabil Aga", "Omar Pasha",
      "Qasim Bey", "Rami Efendi", "Sami Aga", "Tamer Pasha", "Usama Bey",
      "Walid Efendi", "Yasser Aga", "Ziad Pasha", "Amr Bey", "Bassam Efendi",
      "Fares Aga", "Hazem Pasha", "Imad Bey", "Jihad Efendi", "Karam Aga",
      "Mazen Pasha", "Nizar Bey", "Osama Efendi", "Qusay Aga", "Riad Pasha",
      "Shadi Bey", "Talal Efendi", "Uday Aga", "Wael Pasha", "Yasir Bey",
      "Ziyad Efendi", "Amjad Aga", "Bilal Pasha", "Fadi Bey", "Ghassan Efendi",
      "Hani Aga", "Iyad Pasha", "Jad Bey", "Khaled Efendi", "Laith Aga"
    ],
    female: [
      "Ayşe Hanım", "Fatma Sultan", "Zeynep Hatun", "Safiye Hanım", "Mihrimah Sultan",
      "Hürrem Hatun", "Gülbahar Hanım", "Nurbanu Sultan", "Raziye Hatun", "Şah Hanım",
      "Turhan Sultan", "Ümmi Hatun", "Valide Hanım", "Yasemin Sultan", "Zübeyde Hatun",
      "Aynur Hanım", "Belkıs Sultan", "Cemile Hatun", "Dilara Hanım", "Esma Sultan",
      "Feride Hatun", "Gönül Hanım", "Hatice Sultan", "İnci Hatun", "Jale Hanım",
      "Kamile Sultan", "Leyla Hatun", "Melek Hanım", "Nesrin Sultan", "Özlem Hatun",
      "Pınar Hanım", "Rukiye Sultan", "Sema Hatun", "Tülay Hanım", "Ülkü Sultan",
      "Vildan Hatun", "Yıldız Hanım", "Zeliha Sultan", "Aslı Hatun", "Berna Hanım",
      "Canan Sultan", "Derya Hatun", "Elif Hanım", "Figen Sultan", "Gizem Hatun",
      "Hande Hanım", "İrem Sultan", "Jülide Hatun", "Kübra Hanım", "Lale Sultan",
      "Meral Hatun", "Nalan Hanım", "Oya Sultan", "Pelin Hatun", "Reyhan Hanım",
      "Sibel Sultan", "Tuba Hatun", "Ufuk Hanım", "Vesile Sultan", "Yelda Hatun"
    ]
  },

  cardiel: {
    male: [
      "Alfonso de Córdoba", "Rodrigo ibn Yusuf", "Fernando al-Andalusi", "Diego ben Nasr",
      "Carlos ibn Rushd", "Miguel al-Qurtubi", "Pedro ben Gabirol", "Juan ibn Hazm",
      "Luis al-Mu'tamid", "Antonio ben Ezra", "Francisco ibn Tufayl", "Rafael al-Zarqali",
      "Gabriel ben Maimon", "Andrés ibn Bajja", "Tomás al-Idrisi", "Sebastián ben Tibbon",
      "Alejandro ibn Arabi", "Nicolás al-Bitruji", "Joaquín ben Rushd", "Esteban ibn Quzman",
      "Gonzalo al-Himyari", "Bernardo ben Paquda", "Ramón ibn Masarra", "Enrique al-Qabri",
      "Martín ben Naghrela", "Álvaro ibn Firnas", "Cristóbal al-Hakam", "Salvador ben Shaprut",
      "Ignacio ibn Sina", "Patricio al-Kindi", "Domingo ben Hanoch", "Agustín ibn Rushd",
      "Vicente al-Farabi", "Teodoro ben Gaon", "Leandro ibn Khaldun", "Maximiliano al-Ghazali",
      "Octavio ben Ezra", "Valentín ibn Taimiya", "Casimiro al-Tabari", "Demetrio ben Maimon",
      "Eugenio ibn Battuta", "Florencio al-Masudi", "Gregorio ben Tibbon", "Hipólito ibn Arabi",
      "Isidoro al-Biruni", "Jerónimo ben Rushd", "Laureano ibn Sina", "Marcelino al-Razi",
      "Norberto ben Paquda", "Olegario ibn Masarra", "Plácido al-Jahiz", "Quintiliano ben Gabirol"
    ],
    female: [
      "Isabel de Sevilla", "María ibn Zahra", "Carmen al-Zahra", "Ana ben Sarah",
      "Teresa ibn Maryam", "Pilar al-Andalusia", "Rosa ben Miriam", "Dolores ibn Fatima",
      "Mercedes al-Qurtubiya", "Esperanza ben Rahel", "Concepción ibn Aisha", "Amparo al-Zaynab",
      "Remedios ben Esther", "Soledad ibn Khadija", "Milagros al-Maryam", "Asunción ben Judith",
      "Encarnación ibn Zaynab", "Purificación al-Sarah", "Inmaculada ben Miriam", "Angustias ibn Fatima",
      "Consolación al-Aisha", "Presentación ben Rahel", "Anunciación ibn Maryam", "Visitación al-Zahra",
      "Natividad ben Sarah", "Epifanía ibn Miriam", "Candelaria al-Fatima", "Ascensión ben Esther",
      "Asunción ibn Zaynab", "Tránsito al-Khadija", "Rosario ben Judith", "Piedad ibn Aisha",
      "Caridad al-Maryam", "Esperanza ben Sarah", "Fe ibn Miriam", "Luz al-Zahra",
      "Paz ben Fatima", "Alegría ibn Rahel", "Gloria al-Zaynab", "Victoria ben Esther",
      "Gracia ibn Khadija", "Clemencia al-Aisha", "Paciencia ben Maryam", "Prudencia ibn Sarah",
      "Constancia al-Miriam", "Perseverancia ben Zahra", "Fortaleza ibn Fatima", "Templanza al-Rahel",
      "Justicia ben Zaynab", "Sabiduría ibn Esther", "Castidad al-Khadija", "Humildad ben Judith"
    ]
  },

  english: {
    male: [
      "William MacLeod", "Robert Stewart", "James Campbell", "Alexander MacDonald", "Duncan Fraser",
      "Kenneth MacKenzie", "Malcolm Gordon", "Angus MacPherson", "Donald Cameron", "Hamish MacLean",
      "Alasdair MacGregor", "Roderick MacNeil", "Iain MacKay", "Torquil MacAulay", "Ruaridh MacRae",
      "Calum MacInnes", "Finlay MacBeth", "Gregor MacFarlane", "Hector MacMillan", "Lachlan MacQueen",
      "Magnus MacSween", "Neil MacArthur", "Oran MacBride", "Padraig MacColl", "Quintin MacEwen",
      "Ranald MacGillivray", "Seamus MacIver", "Tavish MacLachlan", "Uisdean MacMhuirich", "Uilleam MacNab",
      "Arthur Sinclair", "Bartholomew Douglas", "Crispin Mowbray", "Edmund Balliol", "Frederick Bruce",
      "Geoffrey Comyn", "Hugh de Morville", "Ingram de Umfraville", "John de Warenne", "Laurence Oliphant",
      "Matthew de Soulis", "Nicholas de Brus", "Osbert FitzGilbert", "Philip de Mowbray", "Quincy de Beaumont",
      "Ralph de Monthermer", "Simon Fraser", "Thomas Randolph", "Uchtred of Galloway", "Walter Stewart",
      "Aymer de Valence", "Bernard de Balliol", "Colin Campbell", "David de Strathbogie", "Eustace de Vesci",
      "Fulk FitzWarin", "Gilbert de Clare", "Henry de Percy", "Ingram de Guines", "John Comyn"
    ],
    female: [
      "Margaret MacLeod", "Isabella Stewart", "Catherine Campbell", "Mary MacDonald", "Janet Fraser",
      "Morag MacKenzie", "Fiona Gordon", "Aileas MacPherson", "Caoimhe Cameron", "Sine MacLean",
      "Iseabail MacGregor", "Marsaili MacNeil", "Mairi MacKay", "Oighrig MacAulay", "Peigi MacRae",
      "Ciorstaidh MacInnes", "Eilidh MacBeth", "Gormlaith MacFarlane", "Una MacMillan", "Beathag MacQueen",
      "Caristiona MacSween", "Deirdre MacArthur", "Eithne MacBride", "Fionnuala MacColl", "Grainne MacEwen",
      "Honora MacGillivray", "Iona MacIver", "Kenna MacLachlan", "Liusaidh MacMhuirich", "Mairead MacNab",
      "Eleanor Sinclair", "Beatrice Douglas", "Christiana Mowbray", "Devorgilla Balliol", "Euphemia Bruce",
      "Galiena Comyn", "Hawise de Morville", "Idonea de Umfraville", "Juliana de Warenne", "Laderina Oliphant",
      "Marjorie de Soulis", "Nichola de Brus", "Orabilis FitzGilbert", "Petronilla de Mowbray", "Quenilda de Beaumont",
      "Rohese de Monthermer", "Sibilla Fraser", "Thomasina Randolph", "Uchtred of Galloway", "Waltheof Stewart",
      "Alianore de Valence", "Bertha de Balliol", "Cecilia Campbell", "Dervorguilla de Strathbogie", "Eva de Vesci",
      "Felicia FitzWarin", "Gwenllian de Clare", "Hawisa de Percy", "Ida de Guines", "Joan Comyn"
    ]
  },

  japanese: {
    male: [
      "Takeshi Yamamoto", "Hiroshi Tanaka", "Kenji Sato", "Masato Suzuki", "Noboru Watanabe",
      "Osamu Ito", "Ryoichi Nakamura", "Shinji Kobayashi", "Taro Kato", "Yuki Yoshida",
      "Akira Hayashi", "Daichi Ishii", "Fumio Yamazaki", "Goro Mori", "Hideo Inoue",
      "Ichiro Kimura", "Jiro Hayakawa", "Kazuo Sasaki", "Makoto Shimizu", "Naoto Yamaguchi",
      "Ryu Matsumoto", "Satoshi Inoue", "Tetsuya Takahashi", "Ushio Endo", "Yoshio Fujiwara",
      "Zhang Wei", "Li Ming", "Wang Qiang", "Liu Gang", "Chen Jun",
      "Yang Lei", "Zhao Bin", "Zhou Tao", "Wu Hao", "Xu Feng",
      "Sun Jian", "Ma Long", "Zhu Kai", "Guo Peng", "He Dong",
      "Lin Yu", "Luo Xin", "Song Bo", "Tang Hui", "Deng Chao",
      "Fan Jun", "Gao Ming", "Han Lei", "Jiang Wei", "Kong Fei",
      "Liang Hao", "Meng Qiang", "Nie Gang", "Ou Yang", "Pan Bin",
      "Qian Tao", "Ren Feng", "Shi Jian", "Tian Long", "Wang Yu"
    ],
    female: [
      "Akiko Yamamoto", "Yuki Tanaka", "Keiko Sato", "Michiko Suzuki", "Noriko Watanabe",
      "Reiko Ito", "Sachiko Nakamura", "Tomoko Kobayashi", "Yoko Kato", "Kazuko Yoshida",
      "Emiko Hayashi", "Fumiko Ishii", "Haruko Yamazaki", "Ikuko Mori", "Junko Inoue",
      "Kimiko Kimura", "Mariko Hayakawa", "Naoko Sasaki", "Rikako Shimizu", "Sayoko Yamaguchi",
      "Takako Matsumoto", "Umeko Inoue", "Wakako Takahashi", "Yasuko Endo", "Yukiko Fujiwara",
      "Li Mei", "Wang Xiu", "Zhang Li", "Liu Fang", "Chen Hua",
      "Yang Min", "Zhao Yan", "Zhou Jing", "Wu Na", "Xu Hong",
      "Sun Ping", "Ma Qin", "Zhu Rui", "Guo Xia", "He Lan",
      "Lin Dan", "Luo Ying", "Song Mei", "Tang Li", "Deng Yu",
      "Fan Ning", "Gao Xin", "Han Yun", "Jiang Fei", "Kong Hui",
      "Liang Jie", "Meng Xuan", "Nie Qing", "Ou Shan", "Pan Rong",
      "Qian Wen", "Ren Xiang", "Shi Yao", "Tian Zhen", "Wang Ai"
    ]
  },



  araterre: {
    male: [
      "Jean-Baptiste Dubois", "Pierre-Alexandre Martin", "François-Xavier Bernard", "Louis-Philippe Moreau",
      "Antoine-Marie Petit", "Charles-Henri Robert", "Michel-André Richard", "Philippe-Joseph Durand",
      "Guillaume-François Leroy", "Nicolas-Claude Moreau", "Étienne-Paul Simon", "Julien-Marc Laurent",
      "Sébastien-Luc Lefebvre", "Matthieu-René Roux", "Olivier-Jean Fournier", "Raphaël-Pierre Dupont",
      "Thierry-Louis Mercier", "Vincent-Paul Blanchard", "Xavier-Marie Girard", "Yves-Claude Bonnet",
      "Alain-François Rousseau", "Bruno-Michel Garnier", "Cédric-André Fabre", "Damien-Philippe Barbier",
      "Émile-Joseph Renard", "Fabrice-Henri Fontaine", "Gaston-Pierre Chevalier", "Hervé-Louis Bertrand",
      "Ignace-Marie Leclerc", "Jacques-Paul Masson", "Lucien-François Morel", "Marcel-André Giraud",
      "Norbert-Philippe Perrin", "Octave-Joseph Picard", "Pascal-Henri Jacquet", "Quentin-Marie Guerin",
      "Rémi-Louis Muller", "Stéphane-Paul Henry", "Tristan-François Roussel", "Urbain-Philippe Nicolas",
      "Valentin-André Faure", "William-Marie Blanc", "Yann-Joseph Guichard", "Zacharie-Louis Fernandez",
      "Armand-Pierre Gonzalez", "Bastien-François Lopez", "Clément-Marie Sanchez", "Dorian-Philippe Perez",
      "Edouard-Joseph Garcia", "Florian-Henri Rodriguez", "Gaël-Louis Martinez", "Hugo-Marie Hernandez"
    ],
    female: [
      "Marie-Claire Dubois", "Anne-Sophie Martin", "Catherine-Élise Bernard", "Dominique-Marie Moreau",
      "Élisabeth-Anne Petit", "Françoise-Claire Robert", "Geneviève-Marie Richard", "Hélène-Sophie Durand",
      "Isabelle-Anne Leroy", "Jacqueline-Marie Moreau", "Karine-Claire Simon", "Laurence-Sophie Laurent",
      "Monique-Anne Lefebvre", "Nathalie-Marie Roux", "Odile-Claire Fournier", "Pascale-Sophie Dupont",
      "Régine-Anne Mercier", "Sylvie-Marie Blanchard", "Thérèse-Claire Girard", "Ursule-Sophie Bonnet",
      "Véronique-Anne Rousseau", "Wanda-Marie Garnier", "Ximena-Claire Fabre", "Yolande-Sophie Barbier",
      "Zoé-Anne Renard", "Agnès-Marie Fontaine", "Brigitte-Claire Chevalier", "Cécile-Sophie Bertrand",
      "Denise-Anne Leclerc", "Estelle-Marie Masson", "Fabienne-Claire Morel", "Ghislaine-Sophie Giraud",
      "Huguette-Anne Perrin", "Irène-Marie Picard", "Josette-Claire Jacquet", "Laure-Sophie Guerin",
      "Madeleine-Anne Muller", "Nadine-Marie Henry", "Ophélie-Claire Roussel", "Paulette-Sophie Nicolas",
      "Quitterie-Anne Faure", "Roseline-Marie Blanc", "Solange-Claire Guichard", "Tatiana-Sophie Fernandez",
      "Ursule-Anne Gonzalez", "Viviane-Marie Lopez", "Winifred-Claire Sanchez", "Xavière-Sophie Perez",
      "Yseult-Anne Garcia", "Zélie-Marie Rodriguez", "Apolline-Claire Martinez", "Bénédicte-Sophie Hernandez"
    ]
  },

  Orcs: {
    male: [
      "Grishnak Bloodfang", "Ugluk Ironjaw", "Azog Defiler", "Bolg Spawn", "Gothmog Lieutenant",
      "Lurtz Uruk", "Shagrat Captain", "Gorbag Tracker", "Mauhur Scout", "Snaga Grunt",
      "Grishnakh Raider", "Muzgash Warrior", "Ufthak Guard", "Radbug Archer", "Lagduf Spear",
      "Golfimbul Chief", "Yazneg Hunter", "Fimbul Rider", "Narzug Tracker", "Boldog Commander",
      "Gundabad King", "Dushnamub Warlord", "Pushkrimp Berserker", "Ghash Cleaver", "Grublik Smasher",
      "Snafu Brawler", "Ugluk Bruiser", "Grishnak Slayer", "Azog Destroyer", "Bolg Crusher",
      "Gothmog Butcher", "Lurtz Killer", "Shagrat Ripper", "Gorbag Render", "Mauhur Tearer",
      "Snaga Gnawer", "Grishnakh Biter", "Muzgash Chomper", "Ufthak Mauler", "Radbug Piercer",
      "Lagduf Stabber", "Golfimbul Hacker", "Yazneg Slasher", "Fimbul Chopper", "Narzug Carver",
      "Boldog Splitter", "Gundabad Breaker", "Dushnamub Wrecker", "Pushkrimp Demolisher", "Ghash Annihilator",
      "Grublik Devastator", "Snafu Obliterator", "Ugluk Exterminator", "Grishnak Eradicator", "Azog Eliminator",
      "Bolg Terminator", "Gothmog Liquidator", "Lurtz Executioner", "Shagrat Assassin", "Gorbag Murderer"
    ],
    female: [
      "Grishnaka Bloodfang", "Ugluka Ironjaw", "Azoga Defiler", "Bolga Spawn", "Gothmoga Lieutenant",
      "Lurtza Uruk", "Shagrata Captain", "Gorbaga Tracker", "Mauhura Scout", "Snagga Grunt",
      "Grishnakha Raider", "Muzgasha Warrior", "Ufthaka Guard", "Radbuga Archer", "Lagdufa Spear",
      "Golfimbula Chief", "Yaznaga Hunter", "Fimbula Rider", "Narzuga Tracker", "Boldoga Commander",
      "Gundabada King", "Dushnamuba Warlord", "Pushkrimpa Berserker", "Ghasha Cleaver", "Grublika Smasher",
      "Snafua Brawler", "Ugluka Bruiser", "Grishnaka Slayer", "Azoga Destroyer", "Bolga Crusher",
      "Gothmoga Butcher", "Lurtza Killer", "Shagrata Ripper", "Gorbaga Render", "Mauhura Tearer",
      "Snagga Gnawer", "Grishnakha Biter", "Muzgasha Chomper", "Ufthaka Mauler", "Radbuga Piercer",
      "Lagdufa Stabber", "Golfimbula Hacker", "Yaznaga Slasher", "Fimbula Chopper", "Narzuga Carver",
      "Boldoga Splitter", "Gundabada Breaker", "Dushnamuba Wrecker", "Pushkrimpa Demolisher", "Ghasha Annihilator",
      "Grublika Devastator", "Snafua Obliterator", "Ugluka Exterminator", "Grishnaka Eradicator", "Azoga Eliminator",
      "Bolga Terminator", "Gothmoga Liquidator", "Lurtza Executioner", "Shagrata Assassin", "Gorbaga Murderer",
      "Urka Bloodthirsty", "Grima Skullcrusher", "Burzum Bonegnawer", "Sharku Fleshripper", "Lagdush Eyegouger"
    ]
  },

  "nomad-territories": {
    male: [
      "Ragnar Ironwolf", "Bjorn Stormcrow", "Erik Bloodaxe", "Olaf Dragonslayer", "Magnus Thunderfist",
      "Gunnar Ravensword", "Thorvald Iceheart", "Leif Seawanderer", "Hakon Goldbeard", "Sigurd Snakeye",
      "Ivar Boneless", "Halfdan Whiteshirt", "Ubbe Ragnarsson", "Hvitserk Ironside", "Rollo Walkerganger",
      "Floki Boatbuilder", "Athelstan Monk", "Ecbert Wessex", "Aethelwulf Prince", "Alfred Great",
      "Torstein Kuggason", "Arne Riisøya", "Tostig Godwinson", "Harald Hardrada", "Sweyn Forkbeard",
      "Cnut Canute", "Edmund Ironside", "Edward Confessor", "Harold Godwinson", "William Conqueror",
      "Conn Cétchathach", "Niall Noígiallach", "Brian Boru", "Máel Sechnaill", "Domnall Brecc",
      "Áed Findliath", "Flann Sinna", "Muirchertach Leather", "Toirdelbach Ua", "Ruaidrí Ua",
      "Diarmait MacMurrough", "Strongbow Clare", "Aodhán MacRuaidhrí", "Cathal Crobhdearg", "Fedlimid mac",
      "Cormac MacCarthy", "Donnchadh Cairbre", "Muiris Fitzgerald", "Tadhg MacCarthy", "Donal Cam",
      "Fionn MacCumhaill", "Oisín Poet", "Cú Chulainn", "Fergus MacRóich", "Conall Cernach",
      "Lugh Lámhfhada", "Nuada Airgetlám", "Manannán MacLir", "Brigid Goddess", "Dian Cécht",
      "Alton Appleblossom",
  "Alton Brightfoot",
  "Alton Elderberry",
  "Alton Fernhill",
  "Alton Highhill",
  "Alton Oatburrow",
  "Alton Puddlejumper",
  "Alton Quickstep",
  "Alton Softmeadow",
  "Alton Tealeaf",
  "Alton Thistlewhip",
  "Alton Thorngage",
  "Alton Timberfall",
  "Alton Underbough",
  "Alton Willowrush",
  "Alton Wimblestout",
  "Ander Cloverfield",
  "Ander Elderberry",
  "Ander Fernhill",
  "Ander Goodbarrel",
  "Ander Highhill",
  "Ander Merrythorn",
  "Ander Oatburrow",
  "Ander Puddlejumper",
  "Ander Reedwhistle",
  "Ander Tealeaf",
  "Ander Thistlewhip",
  "Ander Underbough",
  "Ander Willowrush",
  "Barrin Boulderdown",
  "Barrin Cloverfield",
  "Barrin Goodbarrel",
  "Barrin Highhill",
  "Barrin Hilltopple",
  "Barrin Leagallow",
  "Barrin Merrythorn",
  "Barrin Oatburrow",
  "Barrin Puddlejumper",
  "Barrin Rumblespring",
  "Barrin Softmeadow",
  "Barrin Sunmeadow",
  "Barrin Tealeaf",
  "Barrin Thistlewhip",
  "Barrin Timberfall",
  "Barrin Underbough",
  "Barrin Warmwater",
  "Barrin Willowrush",
  "Barrin Wimblestout",
  "Brom Appleblossom",
  "Brom Cloverfield",
  "Brom Elderberry",
  "Brom Goldleaf",
  "Brom Highhill",
  "Brom Leagallow",
  "Brom Oatburrow",
  "Brom Quickstep",
  "Brom Reedwhistle",
  "Brom Softmeadow",
  "Brom Sunmeadow",
  "Brom Thistlewhip",
  "Brom Thorngage",
  "Brom Underbough",
  "Cade Boulderdown",
  "Cade Brightfoot",
  "Cade Cloverfield",
  "Cade Elderberry",
  "Cade Goodbarrel",
  "Cade Greenbottle",
  "Cade Hilltopple",
  "Cade Leagallow",
  "Cade Tealeaf",
  "Cade Warmwater",
  "Corrin Appleblossom",
  "Corrin Elderberry",
  "Corrin Fernhill",
  "Corrin Greenbottle",
  "Corrin Leagallow",
  "Corrin Merrythorn",
  "Corrin Oatburrow",
  "Corrin Quickstep",
  "Corrin Reedwhistle",
  "Corrin Timberfall",
  "Corrin Underbough",
  "Corrin Warmwater",
  "Corrin Willowrush",
  "Darin Boulderdown",
  "Darin Brightfoot",
  "Darin Brushgather",
  "Darin Cloverfield",
  "Darin Fernhill",
  "Darin Hayward",
  "Darin Highhill",
  "Darin Merrythorn",
  "Darin Oatburrow",
  "Darin Puddlejumper",
  "Darin Quickstep",
  "Darin Reedwhistle",
  "Darin Softmeadow",
  "Darin Tealeaf",
  "Darin Thistlewhip",
  "Darin Timberfall",
  "Darin Warmwater",
  "Darin Willowrush",
  "Dobel Appleblossom",
  "Dobel Boulderdown",
  "Dobel Greenbottle",
  "Dobel Leagallow",
  "Dobel Merrythorn",
  "Dobel Oatburrow",
  "Dobel Quickstep",
  "Dobel Reedwhistle",
  "Dobel Rumblespring",
  "Dobel Tealeaf",
  "Dobel Thorngage",
  "Dobel Underbough",
  "Dobel Warmwater",
  "Dobel Willowrush",
  "Dobel Wimblestout",
  "Eldon Boulderdown",
  "Eldon Brushgather",
  "Eldon Greenbottle",
  "Eldon Hilltopple",
  "Eldon Oatburrow",
  "Eldon Rumblespring",
  "Eldon Softmeadow",
  "Eldon Sunmeadow",
  "Eldon Tealeaf",
  "Errich Brightfoot",
  "Errich Elderberry",
  "Errich Fernhill",
  "Errich Goldleaf",
  "Errich Oatburrow",
  "Errich Quickstep",
  "Errich Thistlewhip",
  "Errich Underbough",
  "Errich Warmwater",
  "Errich Wimblestout",
  "Finnan Appleblossom",
  "Finnan Boulderdown",
  "Finnan Brightfoot",
  "Finnan Brushgather",
  "Finnan Elderberry",
  "Finnan Hilltopple",
  "Finnan Leagallow",
  "Finnan Merrythorn",
  "Finnan Puddlejumper",
  "Finnan Reedwhistle",
  "Finnan Rumblespring",
  "Finnan Sunmeadow",
  "Finnan Warmwater",
  "Finnan Willowrush",
  "Garret Appleblossom",
  "Garret Boulderdown",
  "Garret Brightfoot",
  "Garret Fernhill",
  "Garret Greenbottle",
  "Garret Hayward",
  "Garret Hilltopple",
  "Garret Leagallow",
  "Garret Oatburrow",
  "Garret Reedwhistle",
  "Garret Tealeaf",
  "Garret Thorngage",
  "Garret Underbough",
  "Garret Wimblestout",
  "Jasper Brightfoot",
  "Jasper Cloverfield",
  "Jasper Fernhill",
  "Jasper Goldleaf",
  "Jasper Hilltopple",
  "Jasper Leagallow",
  "Jasper Puddlejumper",
  "Jasper Tealeaf",
  "Jasper Thorngage",
  "Jasper Timberfall",
  "Jasper Willowrush",
  "Jasper Wimblestout",
  "Lindal Brightfoot",
  "Lindal Hilltopple",
  "Lindal Oatburrow",
  "Lindal Puddlejumper",
  "Lindal Reedwhistle",
  "Lindal Rumblespring",
  "Lindal Tealeaf",
  "Lindal Thorngage",
  "Lindal Timberfall",
  "Lindal Warmwater",
  "Lyle Appleblossom",
  "Lyle Boulderdown",
  "Lyle Cloverfield",
  "Lyle Elderberry",
  "Lyle Goldleaf",
  "Lyle Hilltopple",
  "Lyle Leagallow",
  "Lyle Merrythorn",
  "Lyle Puddlejumper",
  "Lyle Reedwhistle",
  "Lyle Rumblespring",
  "Lyle Softmeadow",
  "Lyle Warmwater",
  "Lyle Willowrush",
  "Merric Appleblossom",
  "Merric Brushgather",
  "Merric Fernhill",
  "Merric Goldleaf",
  "Merric Hayward",
  "Merric Merrythorn",
  "Merric Quickstep",
  "Merric Reedwhistle",
  "Merric Rumblespring",
  "Merric Thistlewhip",
  "Merric Wimblestout",
  "Milo Boulderdown",
  "Milo Brightfoot",
  "Milo Brushgather",
  "Milo Cloverfield",
  "Milo Elderberry",
  "Milo Fernhill",
  "Milo Goldleaf",
  "Milo Greenbottle",
  "Milo Highhill",
  "Milo Hilltopple",
  "Milo Oatburrow",
  "Milo Puddlejumper",
  "Milo Quickstep",
  "Milo Rumblespring",
  "Milo Softmeadow",
  "Milo Sunmeadow",
  "Milo Thorngage",
  "Milo Warmwater",
  "Milo Willowrush",
  "Osborn Boulderdown",
  "Osborn Goldleaf",
  "Osborn Goodbarrel",
  "Osborn Merrythorn",
  "Osborn Quickstep",
  "Osborn Rumblespring",
  "Osborn Softmeadow",
  "Osborn Sunmeadow",
  "Osborn Tealeaf",
  "Osborn Thorngage",
  "Osborn Underbough",
  "Osborn Wimblestout",
  "Perrin Brightfoot",
  "Perrin Cloverfield",
  "Perrin Fernhill",
  "Perrin Goodbarrel",
  "Perrin Greenbottle",
  "Perrin Hayward",
  "Perrin Leagallow",
  "Perrin Puddlejumper",
  "Perrin Reedwhistle",
  "Perrin Softmeadow",
  "Perrin Warmwater",
  "Quint Boulderdown",
  "Quint Cloverfield",
  "Quint Goodbarrel",
  "Quint Sunmeadow",
  "Quint Tealeaf",
  "Quint Thistlewhip",
  "Quint Timberfall",
  "Quint Warmwater",
  "Quint Willowrush",
  "Quint Wimblestout",
  "Reed Boulderdown",
  "Reed Cloverfield",
  "Reed Greenbottle",
  "Reed Hilltopple",
  "Reed Leagallow",
  "Reed Merrythorn",
  "Reed Quickstep",
  "Reed Tealeaf",
  "Reed Warmwater",
  "Reed Wimblestout",
  "Roscoe Boulderdown",
  "Roscoe Brightfoot",
  "Roscoe Goldleaf",
  "Roscoe Goodbarrel",
  "Roscoe Greenbottle",
  "Roscoe Hayward",
  "Roscoe Hilltopple",
  "Roscoe Oatburrow",
  "Roscoe Puddlejumper",
  "Roscoe Quickstep",
  "Roscoe Reedwhistle",
  "Roscoe Tealeaf",
  "Roscoe Thorngage",
  "Roscoe Warmwater",
  "Roscoe Willowrush",
  "Roscoe Wimblestout",
  "Samlen Boulderdown",
  "Samlen Brightfoot",
  "Samlen Brushgather",
  "Samlen Cloverfield",
  "Samlen Goodbarrel",
  "Samlen Hilltopple",
  "Samlen Merrythorn",
  "Samlen Puddlejumper",
  "Samlen Reedwhistle",
  "Samlen Rumblespring",
  "Samlen Softmeadow",
  "Samlen Sunmeadow",
  "Samlen Thistlewhip",
  "Samlen Thorngage",
  "Samlen Underbough",
  "Samlen Warmwater",
  "Samlen Willowrush",
  "Talon Appleblossom",
  "Talon Boulderdown",
  "Talon Brushgather",
  "Talon Elderberry",
  "Talon Goodbarrel",
  "Talon Highhill",
  "Talon Merrythorn",
  "Talon Oatburrow",
  "Talon Puddlejumper",
  "Talon Rumblespring",
  "Talon Sunmeadow",
  "Talon Thorngage",
  "Talon Willowrush",
  "Tobias Appleblossom",
  "Tobias Boulderdown",
  "Tobias Brightfoot",
  "Tobias Cloverfield",
  "Tobias Elderberry",
  "Tobias Goldleaf",
  "Tobias Goodbarrel",
  "Tobias Hayward",
  "Tobias Hilltopple",
  "Tobias Leagallow",
  "Tobias Merrythorn",
  "Tobias Quickstep",
  "Tobias Reedwhistle",
  "Tobias Rumblespring",
  "Tobias Softmeadow",
  "Tobias Timberfall",
  "Tobias Warmwater",
  "Tobias Willowrush",
  "Tobias Wimblestout",
  "Ulmo Brushgather",
  "Ulmo Goldleaf",
  "Ulmo Greenbottle",
  "Ulmo Highhill",
  "Ulmo Leagallow",
  "Ulmo Quickstep",
  "Ulmo Rumblespring",
  "Ulmo Sunmeadow",
  "Ulmo Underbough",
  "Ulmo Wimblestout",
  "Wendel Fernhill",
  "Wendel Goldleaf",
  "Wendel Goodbarrel",
  "Wendel Merrythorn",
  "Wendel Oatburrow",
  "Wendel Puddlejumper",
  "Wendel Sunmeadow",
  "Wendel Timberfall",
  "Wendel Underbough",
  "Wendel Warmwater",
  "Wendel Willowrush",
  "Wendel Wimblestout",
  "Wes Boulderdown",
  "Wes Brushgather",
  "Wes Elderberry",
  "Wes Fernhill",
  "Wes Goodbarrel",
  "Wes Greenbottle",
  "Wes Hayward",
  "Wes Highhill",
  "Wes Puddlejumper",
  "Wes Quickstep",
  "Wes Sunmeadow",
  "Wes Thistlewhip",
  "Wes Underbough",
  "Wes Warmwater",
  "Wes Wimblestout",
  "Wilbin Boulderdown",
  "Wilbin Brushgather",
  "Wilbin Fernhill",
  "Wilbin Goodbarrel",
  "Wilbin Hayward",
  "Wilbin Leagallow",
  "Wilbin Oatburrow",
  "Wilbin Puddlejumper",
  "Wilbin Rumblespring",
  "Wilbin Softmeadow",
  "Wilbin Thistlewhip",
  "Wilbin Underbough",
  "Wilbin Warmwater",
  "Wilbin Wimblestout",
  "Zane Appleblossom",
  "Zane Boulderdown",
  "Zane Elderberry",
  "Zane Goodbarrel",
  "Zane Hayward",
  "Zane Puddlejumper",
  "Zane Quickstep",
  "Zane Reedwhistle",
  "Zane Thorngage",
  "Zane Wimblestout",
    ],
    female: [
      "Lagertha Shieldmaiden", "Aslaug Völva", "Siggy Haraldsdottir", "Torvi Jarl", "Helga Floki",
      "Ingrid Witch", "Gunnhild Queen", "Freydis Eriksdottir", "Astrid Slave", "Porunn Warrior",
      "Margrethe Servant", "Judith Princess", "Kwenthrith Queen", "Elsewith Lady", "Aelswith Queen",
      "Thyri Danebod", "Gyda Ragnarsdottir", "Ragnhild Eriksdottir", "Thora Townhart", "Alfhild Pirate",
      "Hervor Angantyr", "Brynhild Valkyrie", "Gudrun Gjuki", "Sigrid Storrada", "Estrid Svendsdatter",
      "Brigid Kildare", "Deirdre Sorrows", "Gráinne Mhaol", "Medb Connacht", "Scáthach Warrior",
      "Aoife Strongbow", "Gormlaith Brian", "Derbforgaill Ua", "Sadhbh Finn", "Niamh Tír",
      "Étaín Echraide", "Fand Manannan", "Macha Goddess", "Morrígan Battle", "Badb Crow",
      "Nemain Frenzy", "Brigantia Goddess", "Epona Horse", "Rhiannon Mabinogi", "Branwen Llŷr",
      "Arianrhod Silver", "Blodeuwedd Flowers", "Ceridwen Cauldron", "Danu Mother", "Eriu Ireland",
      "Banba Ireland", "Fódla Ireland", "Tailltiu Goddess", "Boann River", "Sinann Shannon",
      "Aine Love", "Cliodhna Beauty", "Lir Sea", "Nuala Fairy", "Siobhan God"
    ]
  },

  "southwest-wildlands": {
    male: [
      "Hakim al-Sufi", "Jalal al-Din", "Rumi Balkhi", "Ibn Sina", "Al-Ghazali Tusi",
      "Suhrawardi Maqtul", "Ibn Arabi", "Hafez Shirazi", "Saadi Shirazi", "Omar Khayyam",
      "Attar Nishapur", "Sanai Ghaznavi", "Ansari Herat", "Qushayri Nishapur", "Junayd Baghdad",
      "Bayazid Bistami", "Mansur Hallaj", "Shibli Baghdad", "Nuri Baghdad", "Kharraz Baghdad",
      "Muhasibi Basra", "Tustari Basra", "Wasiti Baghdad", "Razi Tehran", "Tabari Amol",
      "Biruni Khwarezm", "Kindi Kufa", "Farabi Farab", "Avicenna Bukhara", "Averroes Cordoba",
      "Maimonides Cordoba", "Aquinas Paris", "Eckhart Hochheim", "Tauler Strasbourg", "Suso Constance",
      "Ruysbroeck Brussels", "Groote Deventer", "Kempis Kempen", "Gerson Paris", "Cusanus Kues",
      "Ficino Florence", "Pico Mirandola", "Bruno Nola", "Campanella Stilo", "Boehme Goerlitz",
      "Weigel Zschopau", "Franckenberg Ludwigsdorf", "Angelus Silesius", "Spener Frankfurt", "Zinzendorf Herrnhut",
      "Swedenborg Stockholm", "Saint-Martin Amboise", "Pasqually Grenoble", "Willermoz Lyon", "Martinez Pasqually",
      "Cagliostro Palermo", "Saint-Germain Transylvania", "Mesmer Iznang", "Lavater Zurich", "Jung-Stilling Nassau"
    ],
    female: [
      "Rabia al-Adawiyya", "Fatima Nishapur", "Aisha Balkhi", "Zaynab Shirazi", "Maryam Sufi",
      "Khadija Mystic", "Aminah Dervish", "Safiya Qadiriyya", "Hafsa Naqshbandi", "Umm Kulthum",
      "Sakinah Medina", "Ruqayyah Mecca", "Zahra Fatima", "Hawwa Paradise", "Maryam Virgin",
      "Asiya Pharaoh", "Bilqis Sheba", "Zulaykha Yusuf", "Hajar Ibrahim", "Sarah Abraham",
      "Rebekah Isaac", "Rachel Jacob", "Leah Jacob", "Dinah Jacob", "Tamar Judah",
      "Ruth Naomi", "Esther Persia", "Judith Holofernes", "Susanna Babylon", "Anna Prophetess",
      "Elizabeth Baptist", "Mary Magdalene", "Martha Bethany", "Mary Bethany", "Salome Zebedee",
      "Joanna Chuza", "Susanna Galilee", "Mary Cleopas", "Mary Salome", "Veronica Veil",
      "Helena Constantine", "Monica Augustine", "Macrina Basil", "Syncletica Desert", "Theodora Empress",
      "Radegund Poitiers", "Hilda Whitby", "Brigid Kildare", "Scholastica Benedict", "Clare Assisi",
      "Agnes Bohemia", "Elizabeth Hungary", "Margaret Scotland", "Gertrude Helfta", "Mechtild Magdeburg",
      "Marguerite Porete", "Angela Foligno", "Catherine Siena", "Julian Norwich", "Margery Kempe",
      "Teresa Avila", "Catherine Genoa", "Madame Guyon", "Jeanne Chantal", "Louise Marillac"
    ]
  },

  "aztec": {
    male: [
      "Itzel Kukulkan", "Akbal Jaguar", "Balam Warrior", "Chaac Rainbringer", "Ek Chuah",
      "Hunab Ku", "Itzamna Creator", "Kinich Ahau", "Kukulkan Feathered", "Mulac Offering",
      "Nohoch Ek", "Oxlahun Ok", "Pakal Shield", "Quetzal Bird", "Tecun Uman",
      "Uayeb Unlucky", "Votan Heart", "Wayab Demon", "Xaman Ek", "Yaxkin Sun",
      "Zipacna Earth", "Ahuitzotl Water", "Cipactli Crocodile", "Ehecatl Wind", "Huitzilopochtli War",
      "Mictlantecuhtli Death", "Quetzalcoatl Serpent", "Tezcatlipoca Smoking", "Tlaloc Rain", "Xochiquetzal Flower",
      "Chalchiuhtotolin Turkey", "Coatlicue Serpent", "Coyolxauhqui Moon", "Chicomecoatl Corn", "Itztlacoliuhqui Frost",
      "Mayahuel Agave", "Patecatl Medicine", "Tlazolteotl Filth", "Tonatiuh Sun", "Xipe Totec",
      "Yacatecuhtli Merchants", "Atlacoya Drought", "Chalchiuhtlicue Water", "Cihuacoatl Woman", "Huixtocihuatl Salt",
      "Ilamatecuhtli Old", "Itzpapalotl Obsidian", "Malinalxochitl Grass", "Tzitzimimeh Stars", "Xochitonal Flower",
      "Amimitl Fishing", "Atlaua Fishermen", "Ayauhteotl Mist", "Centzonhuitznahua Stars", "Chalchiuhtecolotl Owl",
      "Chantico Hearth", "Chicomexochitl Seven", "Cihuateteo Women", "Cochimetl Trade", "Coyotlinahual Coyote"
    ],
    female: [
      "Itzela Kukulkan", "Akbala Jaguar", "Balama Warrior", "Chaaca Rainbringer", "Eka Chuah",
      "Hunaba Ku", "Itzamna Creator", "Kinicha Ahau", "Kukulkana Feathered", "Mulaca Offering",
      "Nohocha Ek", "Oxlahuna Ok", "Pakala Shield", "Quetzala Bird", "Tecuna Uman",
      "Uayeba Unlucky", "Votana Heart", "Wayaba Demon", "Xamana Ek", "Yaxkina Sun",
      "Zipacna Earth", "Ahuitzotla Water", "Cipactla Crocodile", "Ehecatla Wind", "Huitzilopochta War",
      "Mictlantecuhtla Death", "Quetzalcoatla Serpent", "Tezcatlipoca Smoking", "Tlaloca Rain", "Xochiquetzala Flower",
      "Chalchiuhtotola Turkey", "Coatlicuea Serpent", "Coyolxauhquia Moon", "Chicomecoatla Corn", "Itztlacoliuhquia Frost",
      "Mayahuala Agave", "Patecatla Medicine", "Tlazolteotla Filth", "Tonatia Sun", "Xipea Totec",
      "Yacatecuhtla Merchants", "Atlacoyaa Drought", "Chalchiuhtlicuea Water", "Cihuacoatla Woman", "Huixtocihuatla Salt",
      "Ilamatecuhtla Old", "Itzpapalotla Obsidian", "Malinalxochitla Grass", "Tzitzimimea Stars", "Xochitona Flower",
      "Amimitla Fishing", "Atluaa Fishermen", "Ayauhteotle Mist", "Centzonhuitznahuaa Stars", "Chalchiuhtecolotla Owl",
      "Chanticoa Hearth", "Chicomexochitla Seven", "Cihuateteoa Women", "Cochimetla Trade", "Coyotlinahuala Coyote",
      "Xilonena Corn", "Citlalia Star", "Itziara Morning", "Nayelia Love", "Quetzalia Beautiful",
      "Tlazohcamati Grateful", "Yaretzia Forever", "Zeltzina Delicate", "Amoxtlia Book", "Cuicatla Song"
    ]
  },

  "tredroy": {
    male: [
      "Marcus ibn Yusuf", "Giovanni al-Masih", "Dimitrios ben Avraham", "Ahmed della Croce", "Mikhail ibn Dawud",
      "Francesco al-Hakim", "Georgios ben Moshe", "Omar della Rosa", "Alexios ibn Ibrahim", "Lorenzo al-Rashid",
      "Theodoros ben Yaakov", "Hassan della Torre", "Nikolas ibn Musa", "Antonio al-Fadil", "Konstantinos ben David",
      "Yusuf della Porta", "Stefanos ibn Hakim", "Matteo al-Mansur", "Ioannes ben Shlomo", "Khalil della Scala",
      "Petros ibn Yaqub", "Giacomo al-Zahir", "Demetrios ben Reuven", "Salim della Fonte", "Vasileios ibn Sulayman",
      "Paolo al-Kamil", "Christos ben Levi", "Tariq della Pietra", "Mikhael ibn Ismail", "Roberto al-Nasir",
      "Georgios ben Gershon", "Farid della Luna", "Alexandros ibn Khalil", "Benedetto al-Mu'izz", "Theodoros ben Shimon",
      "Nasser della Stella", "Ioannes ibn Yahya", "Vincenzo al-Hakeem", "Dimitrios ben Mordechai", "Rashid della Pace",
      "Konstantinos ibn Umar", "Salvatore al-Fadel", "Petros ben Ephraim", "Jamal della Speranza", "Nikolaos ibn Mansur",
      "Francesco al-Zahir", "Georgios ben Naphtali", "Samir della Vittoria", "Alexios ibn Qasim", "Matteo al-Rasheed",
      "Theodoros ben Asher", "Khalid della Gloria", "Ioannes ibn Hakim", "Antonio al-Mu'tamid", "Dimitrios ben Judah",
      "Yusuf della Fortuna", "Stefanos ibn Dawud", "Paolo al-Mansur", "Christos ben Benjamin", "Tariq della Libertà"
    ],
    female: [
      "Maria bint Fatima", "Giovanna al-Zahra", "Theodora bat Sarah", "Aisha della Luce", "Ekaterina bint Maryam",
      "Francesca al-Nur", "Georgia bat Rivka", "Zaynab della Rosa", "Alexandra bint Khadija", "Lucia al-Qamar",
      "Theodora bat Rachel", "Fatima della Torre", "Nikoletta bint Aisha", "Antonia al-Shams", "Konstantina bat Leah",
      "Maryam della Porta", "Stefania bint Zahra", "Mattea al-Najma", "Ioanna bat Miriam", "Khadija della Scala",
      "Petra bint Yasmin", "Giacoma al-Ward", "Demetria bat Esther", "Salma della Fonte", "Vasileia bint Layla",
      "Paula al-Qamar", "Christina bat Deborah", "Tariqah della Pietra", "Mikaela bint Safiya", "Roberta al-Noor",
      "Georgia bat Hannah", "Farida della Luna", "Alexandra bint Halima", "Benedetta al-Badr", "Theodora bat Tamar",
      "Nasira della Stella", "Ioanna bint Zaynab", "Vincenza al-Shams", "Demetria bat Judith", "Rashida della Pace",
      "Konstantina bint Umm", "Salvadora al-Nur", "Petra bat Abigail", "Jamila della Speranza", "Nikoletta bint Layla",
      "Francesca al-Ward", "Georgia bat Dinah", "Samira della Vittoria", "Alexia bint Qasima", "Mattea al-Qamar",
      "Theodora bat Bathsheba", "Khalida della Gloria", "Ioanna bint Hakima", "Antonia al-Shams", "Demetria bat Naomi",
      "Yusra della Fortuna", "Stefania bint Dawuda", "Paula al-Najma", "Christina bat Binyamin", "Tariqa della Libertà"
    ]
  },

  "arabic": {
    male: [
      "Hakim al-Sahra", "Khalil ibn Rimal", "Nasser al-Badawi", "Omar ibn Qafila", "Rashid al-Wahati",
      "Salim ibn Jamal", "Tariq al-Rih", "Yusuf ibn Sarab", "Zaid al-Najm", "Ahmad ibn Dune",
      "Bilal al-Mirage", "Farid ibn Oasis", "Hamza al-Simoom", "Jamal ibn Khaima", "Khalid al-Ghurub",
      "Mansur ibn Shams", "Nabil al-Fajr", "Qasim ibn Layl", "Rami al-Sakin", "Sami ibn Harr",
      "Tamer al-Qaws", "Umar ibn Sayf", "Walid al-Buraq", "Yasir ibn Naga", "Ziyad al-Mahaba",
      "Adel ibn Sabr", "Bassam al-Qadim", "Fares ibn Hikma", "Ghassan al-Sharaf", "Hazem ibn Majd",
      "Imad al-Wafa", "Jihad ibn Sidq", "Karam al-Karim", "Laith ibn Shuja", "Mazen al-Aziz",
      "Nizar ibn Jalil", "Osama al-Habib", "Qusay ibn Amin", "Riad al-Sadiq", "Shadi ibn Latif",
      "Talal al-Zahir", "Uday ibn Munir", "Wael al-Bashir", "Yasir ibn Nadir", "Ziyad al-Qahir",
      "Amjad ibn Fakhr", "Bilal al-Nasir", "Fadi ibn Zafir", "Ghassan al-Mansur", "Hani ibn Qawi",
      "Iyad al-Sabur", "Jad ibn Shakir", "Khaled al-Ghani", "Laith ibn Majid", "Marwan al-Rashid",
      "Nader ibn Salih", "Omar al-Tayyib", "Qais ibn Wahid", "Rami al-Zahid", "Saad ibn Zakir"
    ],
    female: [
      "Amina al-Sahra", "Fatima bint Rimal", "Khadija al-Badawiya", "Maryam bint Qafila", "Nadia al-Wahati",
      "Rania bint Jamal", "Salma al-Rih", "Yasmin bint Sarab", "Zahra al-Najma", "Aisha bint Dune",
      "Bushra al-Mirage", "Dina bint Oasis", "Farah al-Simoom", "Hala bint Khaima", "Iman al-Ghurub",
      "Layla bint Shams", "Mona al-Fajr", "Nour bint Layl", "Reem al-Sakina", "Sahar bint Harr",
      "Widad al-Qaws", "Yasmin bint Sayf", "Zeinab al-Buraq", "Abeer bint Naga", "Dalal al-Mahaba",
      "Fawzia bint Sabr", "Ghada al-Qadima", "Hayat bint Hikma", "Inaam al-Sharafa", "Jihan bint Majd",
      "Kawther al-Wafa", "Lubna bint Sidq", "Manal al-Karima", "Nawal bint Shuja", "Randa al-Aziza",
      "Suha bint Jalil", "Thuraya al-Habiba", "Wafa bint Amin", "Yara al-Sadiqa", "Zara bint Latif",
      "Asma al-Zahira", "Buthaina bint Munir", "Dalia al-Bashira", "Fadia bint Nadir", "Ghaida al-Qahira",
      "Hanan bint Fakhr", "Israa al-Nasira", "Jumana bint Zafir", "Kholoud al-Mansura", "Lina bint Qawi",
      "Maha al-Sabura", "Najla bint Shakir", "Rawan al-Ghaniya", "Sawsan bint Majid", "Taghreed al-Rashida",
      "Wejdan bint Salih", "Yasmina al-Tayyiba", "Zulaikha bint Wahid", "Areej al-Zahida", "Budour bint Zakir"
    ]
  },

  "black-forest": {
    male: [
      "Grimwald Shadowbane", "Thorek Darkbough", "Aldric Nightwhisper", "Bane Corruptor", "Draven Voidheart",
      "Erebus Blackthorn", "Fenris Doomhowl", "Gorthak Blightbringer", "Hades Soulreaper", "Ixion Cursed",
      "Jormun Worldeater", "Kael Darkmoon", "Lucifer Fallen", "Malachar Deathbringer", "Nyx Shadowweaver",
      "Oberon Darkfey", "Phantom Wraith", "Quill Nightscribe", "Raven Blackwing", "Sable Darkheart",
      "Thanatos Death", "Umbra Shadow", "Vex Hexbringer", "Wraith Specter", "Xerath Voidlord",
      "Yorick Gravedigger", "Zephyr Darkwind", "Abaddon Destroyer", "Belial Tormentor", "Cain Kinslayer",
      "Damien Hellspawn", "Erebos Underworld", "Faust Soultrader", "Grimm Reaper", "Hel Goddess",
      "Iblis Deceiver", "Janus Twoface", "Kronos Timeeater", "Loki Trickster", "Mephistopheles Devil",
      "Nemesis Vengeance", "Orcus Undead", "Pazuzu Demon", "Qingu Chaos", "Ravana Demon",
      "Set Chaos", "Typhon Monster", "Uriel Fallen", "Venom Poisoner", "Wendigo Cannibal",
      "Xaphan Fallen", "Ymir Frost", "Zagan Duke", "Asmodeus Prince", "Belphegor Sloth",
      "Caym President", "Dantalion Duke", "Eligos Duke", "Furfur Earl", "Gaap President"
    ],
    female: [
      "Grimhilde Shadowbane", "Thoreka Darkbough", "Aldrica Nightwhisper", "Banshee Corruptor", "Dravena Voidheart",
      "Erebia Blackthorn", "Fenrisa Doomhowl", "Gorthaka Blightbringer", "Hadia Soulreaper", "Ixiona Cursed",
      "Jormuna Worldeater", "Kaela Darkmoon", "Lucifera Fallen", "Malachara Deathbringer", "Nyxa Shadowweaver",
      "Oberona Darkfey", "Phantoma Wraith", "Quilla Nightscribe", "Ravena Blackwing", "Sablea Darkheart",
      "Thanatosa Death", "Umbria Shadow", "Vexa Hexbringer", "Wraitha Specter", "Xeratha Voidlord",
      "Yoricka Gravedigger", "Zephyra Darkwind", "Abaddona Destroyer", "Beliala Tormentor", "Caina Kinslayer",
      "Damiena Hellspawn", "Erebosa Underworld", "Fausta Soultrader", "Grimma Reaper", "Hela Goddess",
      "Iblisa Deceiver", "Janusa Twoface", "Kronosa Timeeater", "Lokia Trickster", "Mephistophela Devil",
      "Nemesisa Vengeance", "Orcusa Undead", "Pazuzua Demon", "Qingua Chaos", "Ravana Demon",
      "Seta Chaos", "Typhona Monster", "Uriela Fallen", "Venoma Poisoner", "Wendiga Cannibal",
      "Xaphana Fallen", "Ymira Frost", "Zagana Duke", "Asmodeusa Prince", "Belphegora Sloth",
      "Cayma President", "Dantalioa Duke", "Eligosa Duke", "Furfura Earl", "Gaapa President"
    ]
  },
  "dwarven": {
    male: [
    "Baldor Barrelgut", "Baldor Flintbeard", "Baldor Forgeblaze", "Baldor Oakenshield", "Baldor Understone",
  "Balin Boulderbreaker", "Balin Brightpick", "Balin Caveguard", "Balin Fireforge", "Balin Flameheart",
  "Balin Goldfinder", "Balin Runesinger", "Balin Steelgrip", "Balin Understone", "Barundar Battleborn",
  "Barundar Blackrock", "Barundar Boulderbreaker", "Barundar Darkdelve", "Barundar Earthrender", "Barundar Runehelm",
  "Belgrim Forgeblaze", "Belgrim Hammerfall", "Belgrim Runeweaver", "Belgrim Shadowmine", "Belgrim Stonefury",
  "Borin Battleborn", "Borin Deepdelver", "Borin Flintbeard", "Borin Granitegrip", "Borin Stormbelly",
  "Bramor Anvilhand", "Bramor Barrelgut", "Bramor Goldmantle", "Bramor Runehelm", "Bramor Underforge",
  "Branak Brightpick", "Branak Frostbeard", "Branak Ironmantle", "Branak Oakensoul", "Branak Strongaxe",
  "Brom Brassmantle", "Brom Coppervein", "Brom Frostmantle", "Brom Gemcutter", "Brom Stonebrow",
  "Brokk Battleborn", "Brokk Flameheart", "Brokk Runesinger", "Brokk Steelshield", "Brokk Thundertoe",
  "Darrak Fireforge", "Darrak Flameheart", "Darrak Frostmantle", "Darrak Goldmantle", "Darrak Underforge",
  "Dorn Blackrock", "Dorn Boulderbreaker", "Dorn Brightpick", "Dorn Rockseeker", "Dorn Thunderforge",
  "Dori Caveguard", "Dori Flameheart", "Dori Frostbeard", "Dori Strongaxe", "Dori Thunderforge",
  "Dromund Embermantle", "Dromund Forgeblaze", "Dromund Frostmantle", "Dromund Runesinger", "Dromund Stormbelly",
  "Durin Boulderbreaker", "Durin Darkdelve", "Durin Flameheart", "Durin Rockmender", "Durin Understone",
  "Durnik Barrelgut", "Durnik Blackrock", "Durnik Brightpick", "Durnik Goldmantle", "Durnik Stonefury",
  "Dûrin Boulderbreaker", "Dûrin Earthrender", "Dûrin Flameheart", "Dûrin Runeweaver", "Dûrin Stormbelly",
  "Fargrim Forgeblaze", "Fargrim Flameheart", "Fargrim Runesinger", "Fargrim Steelgrip", "Fargrim Underforge",
  "Fili Blackrock", "Fili Coppervein", "Fili Deepforge", "Fili Flameheart", "Fili Frostmantle",
  "Fundin Forgeblaze", "Fundin Flameheart", "Fundin Rockmender", "Fundin Thunderforge", "Fundin Understone",
  "Garnick Flameheart", "Garnick Frostbeard", "Garnick Runeweaver", "Garnick Stormbelly", "Garnick Strongaxe",
  "Gimbar Boulderbreaker", "Gimbar Embermantle", "Gimbar Frostbeard", "Gimbar Stonefury", "Gimbar Understone",
  "Gloin Barrelgut", "Gloin Blackrock", "Gloin Flameheart", "Gloin Frostmantle", "Gloin Runeweaver",
  "Grimnur Battleborn", "Grimnur Coppervein", "Grimnur Earthrender", "Grimnur Oakensoul", "Grimnur Underforge",
  "Gromnir Blackrock", "Gromnir Flameheart", "Gromnir Frostmantle", "Gromnir Runeweaver", "Gromnir Understone",
  "Harbek Boulderbreaker", "Harbek Flameheart", "Harbek Runesinger", "Harbek Steelgrip", "Harbek Stormbelly",
  "Hergar Flameheart", "Hergar Granitegrip", "Hergar Hammerfall", "Hergar Runeweaver", "Hergar Strongaxe",
  "Khalin Barrelgut", "Khalin Boulderbreaker", "Khalin Earthrender", "Khalin Forgeblaze", "Khalin Rockseeker",
  "Kazador Brassmantle", "Kazador Brightpick", "Kazador Flameheart", "Kazador Runesinger", "Kazador Understone",
  "Khurin Coppervein", "Khurin Flameheart", "Khurin Frostbeard", "Khurin Strongaxe", "Khurin Understone",
  "Kili Forgeblaze", "Kili Frostbeard", "Kili Goldmantle", "Kili Runehelm", "Kili Underforge",
  "Korvir Flameheart", "Korvir Frostbeard", "Korvir Runeweaver", "Korvir Steelgrip", "Korvir Thunderforge",
  "Kragg Barrelgut", "Kragg Blackrock", "Kragg Flameheart", "Kragg Frostmantle", "Kragg Runeweaver",
  "Krogar Battleborn", "Krogar Deepdelver", "Krogar Fireforge", "Krogar Rockmender", "Krogar Underforge",
  "Marnak Blackrock", "Marnak Boulderbreaker", "Marnak Forgeblaze", "Marnak Frostmantle", "Marnak Understone",
  "Murdain Flameheart", "Murdain Runehelm", "Murdain Steelgrip", "Murdain Thunderforge", "Murdain Underforge",
  "Narak Boulderbreaker", "Narak Coppervein", "Narak Flameheart", "Narak Runeweaver", "Narak Understone",
  "Nori Blackrock", "Nori Flameheart", "Nori Runeweaver", "Nori Stormbelly", "Nori Understone",
  "Norin Barrelgut", "Norin Flameheart", "Norin Frostmantle", "Norin Rockseeker", "Norin Thunderforge",
  "Oin Deepdelver", "Oin Flameheart", "Oin Frostmantle", "Oin Runeweaver", "Oin Underforge",
  "Rogar Barrelgut", "Rogar Brightpick", "Rogar Coppervein", "Rogar Flameheart", "Rogar Runeweaver",
  "Rondal Brassmantle", "Rondal Forgeblaze", "Rondal Hammerfall", "Rondal Oakensoul", "Rondal Runeweaver",
  "Rurik Blackrock", "Rurik Flameheart", "Rurik Frostmantle", "Rurik Runesinger", "Rurik Understone",
  "Sindri Barrelgut", "Sindri Flameheart", "Sindri Runeweaver", "Sindri Stormbelly", "Sindri Underforge",
  "Thaldin Boulderbreaker", "Thaldin Flameheart", "Thaldin Frostmantle", "Thaldin Runeweaver", "Thaldin Understone",
  "Thaldrin Brassmantle", "Thaldrin Coppervein", "Thaldrin Flameheart", "Thaldrin Runeweaver", "Thaldrin Thunderforge",
  "Thorek Battleborn", "Thorek Flameheart", "Thorek Rockmender", "Thorek Runeweaver", "Thorek Understone",
  "Thorgar Forgeblaze", "Thorgar Frostbeard", "Thorgar Runeweaver", "Thorgar Thunderforge", "Thorgar Underforge",
  "Thordek Blackrock", "Thordek Flameheart", "Thordek Rockmender", "Thordek Steelgrip", "Thordek Understone",
  "Thrain Barrelgut", "Thrain Flameheart", "Thrain Frostmantle", "Thrain Runeweaver", "Thrain Understone",
  "Thrain II Brassmantle", "Thrain II Flameheart", "Thrain II Frostmantle", "Thrain II Runeweaver", "Thrain II Thunderforge",
  "Thrainar Coppervein", "Thrainar Forgeblaze", "Thrainar Frostmantle", "Thrainar Runeweaver", "Thrainar Underforge",
  "Torbek Flameheart", "Torbek Runeweaver", "Torbek Steelgrip", "Torbek Underforge", "Torbek Understone",
  "Torbjorn Boulderbreaker", "Torbjorn Flameheart", "Torbjorn Runeweaver", "Torbjorn Steelshield", "Torbjorn Underforge",
  "Ulrik Brassmantle", "Ulrik Flameheart", "Ulrik Runeweaver", "Ulrik Stonefury", "Ulrik Underforge",
  "Ulfgar Brightpick", "Ulfgar Flameheart", "Ulfgar Runeweaver", "Ulfgar Stormbelly", "Ulfgar Understone",
  "Varric Flameheart", "Varric Forgeblaze", "Varric Runeweaver", "Varric Steelgrip", "Varric Understone",
  "Vigrun Battleborn", "Vigrun Boulderbreaker", "Vigrun Flameheart", "Vigrun Frostmantle", "Vigrun Runeweaver",
  "Thorin Ironforge", "Balin Stonebeard", "Dwalin Axebreaker", "Gloin Goldbeard", "Oin Healer",
      "Bifur Craftsman", "Bofur Toymaker", "Bombur Cook", "Dori Merchant", "Nori Thief",
      "Ori Scribe", "Fili Archer", "Kili Warrior", "Gimli Lockbearer", "Borin Longbeard",
      "Dain Ironfoot", "Thrain Oakenshield", "Thror Undermountain", "Nain Redaxe", "Fundin Broadbeam",
      "Groin Firebeard", "Telchar Smith", "Azaghal Belegost", "Khim Nogrod", "Mim Petty-dwarf",
      "Durin Deathless", "Balin Fundinul", "Gloin Groinsson", "Oin Gloinsson", "Nali Dainsson",
      "Frerin Thrain", "Dis Thrain", "Thorek Ironbrow", "Ungrim Ironfist", "Kazador Dragonslayer",
      "Belegar Ironhammer", "Thorgrim Grudgebearer", "Alrik Ranulfsson", "Byrrnoth Grundadrakk", "Grimm Burloksson",
      "Josef Bugman", "Malakai Makaisson", "Gotrek Gurnisson", "Felix Jaeger", "Snorri Nosebiter",
      "Borek Forkbeard", "Grimjaw Skargan", "Kadrin Redmane", "Morgrim Blackbeard", "Rurik Ironforge",
      "Thane Ironbreaker", "Ungrim Slayer", "Valka Ironforge", "Wulfrik Hammerfist", "Yorri Ironbeard",
      "Zhuf Blackhammer", "Alaric Runesmith", "Brok Stonefist", "Dargo Ironfoot", "Eldric Goldbeard"
    ],
    female: [
        "Alfhild Coppervein", "Alfhild Earthrender", "Alfhild Fireforge", "Alfhild Forgeblaze", "Alfhild Gemcutter",
  "Alfhild Ironmantle", "Alfhild Runehelm", "Alfhild Runesinger", "Annika Caveguard", "Annika Ironmantle",
  "Annika Oakensoul", "Annika Rockmender", "Annika Runeweaver", "Astrid Battleborn", "Astrid Blackrock",
  "Astrid Boulderbreaker", "Astrid Flameheart", "Astrid Frostmantle", "Astrid Runeweaver", "Bardryn Brassmantle",
  "Bardryn Darkdelve", "Bardryn Forgeblaze", "Bardryn Frostbeard", "Bardryn Runeweaver", "Bruni Blackrock",
  "Bruni Coppervein", "Bruni Flameheart", "Bruni Runeweaver", "Bruni Underforge", "Brynja Barrelgut",
  "Brynja Brightpick", "Brynja Flameheart", "Brynja Runeweaver", "Brynja Understone", "Dagnal Boulderbreaker",
  "Dagnal Flameheart", "Dagnal Goldmantle", "Dagnal Runeweaver", "Dagnal Stonefury", "Dis Boulderbreaker",
  "Dis Flameheart", "Dis Frostmantle", "Dis Runeweaver", "Dis Understone", "Edda Blackrock", "Edda Coppervein",
  "Edda Runeweaver", "Edda Stormbelly", "Edda Underforge", "Eldeth Barrelgut", "Eldeth Flameheart",
  "Eldeth Runesinger", "Eldeth Strongaxe", "Eldeth Thunderforge", "Falkrunn Flameheart", "Falkrunn Runeweaver",
  "Falkrunn Steelgrip", "Falkrunn Underforge", "Falkrunn Understone", "Finellen Blackrock", "Finellen Flameheart",
  "Finellen Runeweaver", "Finellen Strongaxe", "Finellen Thunderforge", "Freydis Coppervein", "Freydis Forgeblaze",
  "Freydis Runeweaver", "Freydis Stonefury", "Freydis Understone", "Gerta Boulderbreaker", "Gerta Flameheart",
  "Gerta Runeweaver", "Gerta Thunderforge", "Gerta Underforge", "Gudrun Blackrock", "Gudrun Flameheart",
  "Gudrun Runeweaver", "Gudrun Underforge", "Gudrun Understone", "Gunnloda Brightpick", "Gunnloda Flameheart",
  "Gunnloda Runeweaver", "Gunnloda Steelgrip", "Gunnloda Thunderforge", "Helja Coppervein", "Helja Flameheart",
  "Helja Runeweaver", "Helja Strongaxe", "Helja Underforge", "Hilde Blackrock", "Hilde Brassmantle",
  "Hilde Flameheart", "Hilde Runeweaver", "Hilde Understone", "Hlin Boulderbreaker", "Hlin Flameheart",
  "Hlin Runeweaver", "Hlin Thunderforge", "Hlin Underforge", "Ilde Blackrock", "Ilde Coppervein",
  "Ilde Flameheart", "Ilde Runeweaver", "Ilde Underforge", "Ingra Flameheart", "Ingra Runeweaver",
  "Ingra Stonefury", "Ingra Underforge", "Ingra Understone", "Ingrid Blackrock", "Ingrid Coppervein",
  "Ingrid Flameheart", "Ingrid Runeweaver", "Ingrid Thunderforge", "Kathra Brightpick", "Kathra Flameheart",
  "Kathra Runeweaver", "Kathra Steelgrip", "Kathra Underforge", "Kristryd Flameheart", "Kristryd Runeweaver",
  "Kristryd Stonefury", "Kristryd Strongaxe", "Kristryd Thunderforge", "Liftrasa Blackrock", "Liftrasa Coppervein",
  "Liftrasa Flameheart", "Liftrasa Runeweaver", "Liftrasa Underforge", "Mardred Boulderbreaker", "Mardred Forgeblaze",
  "Mardred Runeweaver", "Mardred Strongaxe", "Mardred Thunderforge", "Morgran Coppervein", "Morgran Flameheart",
  "Morgran Runeweaver", "Morgran Underforge", "Morgran Understone", "Oriff Boulderbreaker", "Oriff Flameheart",
  "Oriff Runeweaver", "Oriff Steelgrip", "Oriff Underforge", "Osk Blackrock", "Osk Flameheart", "Osk Runeweaver",
  "Osk Stonefury", "Osk Understone", "Ragnhild Boulderbreaker", "Ragnhild Flameheart", "Ragnhild Runeweaver",
  "Ragnhild Thunderforge", "Ragnhild Understone", "Riswynn Coppervein", "Riswynn Flameheart", "Riswynn Runeweaver",
  "Riswynn Underforge", "Riswynn Understone", "Runa Boulderbreaker", "Runa Forgeblaze", "Runa Runeweaver",
  "Runa Stonefury", "Runa Thunderforge", "Sannl Barrelgut", "Sannl Blackrock", "Sannl Flameheart",
  "Sannl Runeweaver", "Sannl Thunderforge", "Sigrid Brightpick", "Sigrid Flameheart", "Sigrid Runeweaver",
  "Sigrid Steelgrip", "Sigrid Underforge", "Solveig Blackrock", "Solveig Coppervein", "Solveig Flameheart",
  "Solveig Runeweaver", "Solveig Thunderforge", "Svala Brassmantle", "Svala Flameheart", "Svala Runeweaver",
  "Svala Strongaxe", "Svala Thunderforge", "Thuldra Barrelgut", "Thuldra Flameheart", "Thuldra Runeweaver",
  "Thuldra Steelgrip", "Thuldra Thunderforge", "Torbera Brightpick", "Torbera Flameheart", "Torbera Runeweaver",
  "Torbera Stonefury", "Torbera Thunderforge", "Tove Coppervein", "Tove Flameheart", "Tove Runeweaver",
  "Tove Underforge", "Tove Understone", "Vistra Barrelgut", "Vistra Flameheart", "Vistra Runeweaver",
  "Vistra Thunderforge", "Vistra Understone", "Yrsa Blackrock", "Yrsa Coppervein", "Yrsa Flameheart",
  "Yrsa Runeweaver", "Yrsa Underforge", "Ysra Brassmantle", "Ysra Flameheart", "Ysra Runeweaver",
  "Ysra Stonefury", "Ysra Understone", "Yurgunn Battleborn", "Yurgunn Boulderbreaker", "Yurgunn Flameheart",
  "Yurgunn Runeweaver", "Yurgunn Thunderforge",  "Disa Ironforge", "Vera Stonebeard", "Nala Axebreaker", "Gilda Goldbeard", "Orna Healer",
      "Bira Craftsman", "Bora Toymaker", "Bomba Cook", "Dora Merchant", "Nora Thief",
      "Ora Scribe", "Fila Archer", "Kila Warrior", "Gimla Lockbearer", "Bora Longbeard",
      "Dana Ironfoot", "Thrana Oakenshield", "Throra Undermountain", "Nana Redaxe", "Fundina Broadbeam",
      "Grona Firebeard", "Telchara Smith", "Azaghala Belegost", "Khima Nogrod", "Mima Petty-dwarf",
      "Durina Deathless", "Balina Fundinul", "Gloina Groinsson", "Oina Gloinsson", "Nalia Dainsson",
      "Frerina Thrain", "Disa Thrain", "Thoreka Ironbrow", "Ungrima Ironfist", "Kazadora Dragonslayer",
      "Belegara Ironhammer", "Thorgrima Grudgebearer", "Alrika Ranulfsson", "Byrrnatha Grundadrakk", "Grimma Burloksson",
      "Josefa Bugman", "Malakaia Makaisson", "Gotreka Gurnisson", "Felixa Jaeger", "Snorria Nosebiter",
      "Boreka Forkbeard", "Grimjawa Skargan", "Kadrina Redmane", "Morgrima Blackbeard", "Rurika Ironforge",
      "Thanea Ironbreaker", "Ungrima Slayer", "Valkaa Ironforge", "Wulfrika Hammerfist", "Yorria Ironbeard",
      "Zhufa Blackhammer", "Alarica Runesmith", "Broka Stonefist", "Dargoa Ironfoot", "Eldrica Goldbeard"
    ]
  },
  Elfos: {
    male: [
      "Adran Brightglade", "Adran Duskwatcher", "Adran Elensar", "Adran Embermist", "Adran Evendawn",
  "Adran Glowbranch", "Adran Meliamne", "Adran Mistriver", "Adran Moonbrook", "Adran Nightbreeze",
  "Adran Oakmantle", "Adran Sagewillow", "Adran Shadowdancer", "Adran Silvershade", "Adran Siannodel",
  "Adran Silverleaf", "Adran Skysinger", "Adran Starfall", "Adran Stormrider", "Adran Sunshadow",
  "Aelar Brightgrove", "Aelar Dawntracker", "Aelar Evenwood", "Aelar Faelight", "Aelar Farsight",
  "Aelar Galanodel", "Aelar Holimion", "Aelar Ilphelkiir", "Aelar Liadon", "Aelar Lunarglade",
  "Aelar Meliamne", "Aelar Mistgrove", "Aelar Moonbrook", "Aelar Moonwhisper", "Aelar Mythlore",
  "Aelar Naïlo", "Aelar Nightbreeze", "Aelar Shadowmoon", "Aelar Siannodel", "Aelar Silverfrond",
  "Aramil Amastacia", "Aramil Brightglade", "Aramil Dawntracker", "Aramil Duskwatcher", "Aramil Evenwood",
  "Aramil Faelight", "Aramil Farsight", "Aramil Glowbranch", "Aramil Holimion", "Aramil Liadon",
  "Arannis Lightstep", "Arannis Meliamne", "Arannis Mistriver", "Arannis Moonbrook", "Arannis Moonwhisper",
  "Arannis Naïlo", "Arannis Nightbreeze", "Arannis Nightgleam", "Arannis Oakmantle", "Arannis Sagewillow",
  "Aust Shadowdancer", "Aust Shadowmoon", "Aust Siannodel", "Aust Silverfrond", "Aust Silverleaf",
  "Aust Silvershade", "Aust Skysinger", "Aust Starbreeze", "Aust Starfall", "Aust Starglen",
  "Beiro Stormrider", "Beiro Sunshadow", "Beiro Thaloril", "Beiro Trueflight", "Beiro Whisperwind",
  "Berrian Windwalker", "Berrian Windwhisper", "Berrian Xiloscient", "Berrian Amakiir", "Berrian Autumnshade",
  "Carric Brightglade", "Carric Dawntracker", "Carric Duskwatcher", "Carric Evenwood", "Carric Faelight",
  "Carric Farsight", "Carric Galanodel", "Carric Glowbranch", "Carric Holimion", "Carric Ilphelkiir",
  "Elarion Liadon", "Elarion Lightstep", "Elarion Meliamne", "Elarion Mistriver", "Elarion Moonbrook",
  "Elarion Moonwhisper", "Elarion Naïlo", "Elarion Nightbreeze", "Elarion Nightgleam", "Elarion Oakmantle",
  "Erevan Sagewillow", "Erevan Shadowdancer", "Erevan Shadowmoon", "Erevan Siannodel", "Erevan Silverfrond",
  "Erevan Silverleaf", "Erevan Silvershade", "Erevan Skysinger", "Erevan Starbreeze", "Erevan Starfall",
  "Faelar Stormrider", "Faelar Sunshadow", "Faelar Thaloril", "Faelar Trueflight", "Faelar Whisperwind",
  "Galinndan Windwalker", "Galinndan Windwhisper", "Galinndan Xiloscient", "Galinndan Amakiir", "Galinndan Autumnshade",
  "Haemir Brightglade", "Haemir Dawntracker", "Haemir Duskwatcher", "Haemir Evenwood", "Haemir Faelight",
  "Haemir Farsight", "Haemir Galanodel", "Haemir Glowbranch", "Haemir Holimion", "Haemir Ilphelkiir",
  "Heian Liadon", "Heian Lightstep", "Heian Meliamne", "Heian Mistriver", "Heian Moonbrook",
  "Heian Moonwhisper", "Heian Naïlo", "Heian Nightbreeze", "Heian Nightgleam", "Heian Oakmantle",
  "Ilanar Sagewillow", "Ilanar Shadowdancer", "Ilanar Shadowmoon", "Ilanar Siannodel", "Ilanar Silverfrond",
  "Ilanar Silverleaf", "Ilanar Silvershade", "Ilanar Skysinger", "Ilanar Starbreeze", "Ilanar Starfall",
  "Immeral Stormrider", "Immeral Sunshadow", "Immeral Thaloril", "Immeral Trueflight", "Immeral Whisperwind",
  "Ivellios Windwalker", "Ivellios Windwhisper", "Ivellios Xiloscient", "Ivellios Amakiir", "Ivellios Autumnshade",
  "Jhaeros Brightglade", "Jhaeros Dawntracker", "Jhaeros Duskwatcher", "Jhaeros Evenwood", "Jhaeros Faelight",
  "Jhaeros Farsight", "Jhaeros Galanodel", "Jhaeros Glowbranch", "Jhaeros Holimion", "Jhaeros Ilphelkiir",
  "Kaelthorn Liadon", "Kaelthorn Lightstep", "Kaelthorn Meliamne", "Kaelthorn Mistriver", "Kaelthorn Moonbrook",
  "Kaelthorn Moonwhisper", "Kaelthorn Naïlo", "Kaelthorn Nightbreeze", "Kaelthorn Nightgleam", "Kaelthorn Oakmantle",
  "Laucian Sagewillow", "Laucian Shadowdancer", "Laucian Shadowmoon", "Laucian Siannodel", "Laucian Silverfrond",
  "Laucian Silverleaf", "Laucian Silvershade", "Laucian Skysinger", "Laucian Starbreeze", "Laucian Starfall",
  "Mindartis Stormrider", "Mindartis Sunshadow", "Mindartis Thaloril", "Mindartis Trueflight", "Mindartis Whisperwind",
  "Mythanar Windwalker", "Mythanar Windwhisper", "Mythanar Xiloscient", "Mythanar Amakiir", "Mythanar Autumnshade",
  "Nym Brightglade", "Nym Dawntracker", "Nym Duskwatcher", "Nym Evenwood", "Nym Faelight",
  "Nym Farsight", "Nym Galanodel", "Nym Glowbranch", "Nym Holimion", "Nym Ilphelkiir",
  "Olorin Liadon", "Olorin Lightstep", "Olorin Meliamne", "Olorin Mistriver", "Olorin Moonbrook",
  "Olorin Moonwhisper", "Olorin Naïlo", "Olorin Nightbreeze", "Olorin Nightgleam", "Olorin Oakmantle",
  "Paelias Sagewillow", "Paelias Shadowdancer", "Paelias Shadowmoon", "Paelias Siannodel", "Paelias Silverfrond",
  "Paelias Silverleaf", "Paelias Silvershade", "Paelias Skysinger", "Paelias Starbreeze", "Paelias Starfall",
  "Peren Stormrider", "Peren Sunshadow", "Peren Thaloril", "Peren Trueflight", "Peren Whisperwind",
  "Quarion Windwalker", "Quarion Windwhisper", "Quarion Xiloscient", "Quarion Amakiir", "Quarion Autumnshade",
  "Rhovan Brightglade", "Rhovan Dawntracker", "Rhovan Duskwatcher", "Rhovan Evenwood", "Rhovan Faelight",
  "Rhovan Farsight", "Rhovan Galanodel", "Rhovan Glowbranch", "Rhovan Holimion", "Rhovan Ilphelkiir"
      
    ],
    female: [
       "Aerendil Moonwhisper", "Aerinel Silverleaf", "Aessira Windrunner", "Aeweth Starshade", "Ailinel Dawnsinger",
  "Airelen Mistbrook", "Alariel Nightbloom", "Alassea Sunpetal", "Alenya Softglen", "Almare Duskwhisper",
  "Aminiel Snowgaze", "Amriel Lightbranch", "Anariel Brightflame", "Ancalime Silverglen", "Andúnë Stormbrook",
  "Anethwen Dreamleaf", "Anira Goldriver", "Anneth Starfall", "Arieth Shadowdancer", "Arien Emberveil",
  "Ariya Windglen", "Arlith Nightshade", "Arwen Evenstar", "Asael Moonbrook", "Ashtari Rainwhisper",
  "Athala Glimmerfern", "Aurelia Dreamweaver", "Auriel Frostlight", "Avaniel Flamepetal", "Aweneth Starflower",
  "Belwen Skywhisper", "Brianel Moonfern", "Caeriel Mistveil", "Caleneth Lightglen", "Calithra Fernshade",
  "Celebrian Dawnweaver", "Celwen Nightstream", "Ciriel Moonsong", "Ciryawen Dewsong", "Círdaleth Emberwood",
  "Daenira Frostbrook", "Delaneth Ashglen", "Elaria Swiftbrook", "Elbereth Dreamshadow", "Eleniel Brightshade",
  "Elenwe Nightveil", "Elira Dawnsong", "Ellyra Glowfern", "Elrien Deepstream", "Elyana Starwhisper",
  "Emelwen Flamebloom", "Enariel Willowshade", "Eoweth Mistbloom", "Eryndra Fernwhisper", "Estelwen Greenglen",
  "Faelwen Silvermist", "Faeriel Windshade", "Faylen Starshadow", "Fenriel Nightbloom", "Firiel Emberlight",
  "Galadriel Moonpetal", "Galaneth Brightwind", "Gwenniel Stormveil", "Halethra Flamebrook", "Helyra Skyshadow",
  "Idril Moonblossom", "Ilyana Wildbloom", "Iriel Featherbrook", "Isilme Softshade", "Isithra Leafshine",
  "Ithilwen Sunwhisper", "Kaliane Dreamshade", "Kaelira Farsong", "Kethril Whisperglen", "Laerwen Petalshade",
  "Larethiel Windbloom", "Larien Moonstream", "Lelya Whisperleaf", "Lenwea Glowpetal", "Lindariel Silverbrook",
  "Lirael Fernmist", "Lóriel Snowshade", "Lunareth Softwhisper", "Lúthien Starveil", "Maerwen Rainbloom",
  "Maiael Dawnshadow", "Mairwen Cloudshade", "Melariel Nightfern", "Melian Sunbrook", "Mirelen Frostpetal",
  "Moriel Shadowleaf", "Myrriel Icebloom", "Naerwen Windglow", "Naia Starfern", "Nalael Moonfeather",
  "Nariel Darkglen", "Nessael Dawnbloom", "Nimrael Stormshadow", "Nimwen Riverpetal", "Niniel Mistsong",
  "Nolwëa Dreambrook", "Nymeriel Lightshade", "Oloriel Glowglen", "Ondaleth Sunveil", "Orilwen Sparkmist",
  "Pelwen Rainveil", "Quelwen Flamefern", "Raelith Willowwhisper", "Ranyael Starbrook", "Rhianna Featherglen",
  "Rilwen Shadowglen", "Rinael Nightwhisper", "Ryniel Dawnglen", "Saelwen Morningshade", "Salene Moonwhisper",
  "Sariel Sunleaf", "Selariel Glowstream", "Sereniel Fernveil", "Shaelira Lightbloom", "Shaerya Rainshade",
  "Shalana Moonglen", "Shaywen Dreamveil", "Siliel Firebrook", "Silmariel Mistflower", "Silmëa Windbloom",
  "Sirael Nightpetal", "Siriel Softstream", "Soriel Glimmershade", "Sylaria Emberglen", "Syliel Willowmist",
  "Sylvana Starshade", "Taenya Moonfern", "Taliawen Rainshadow", "Tanriel Brightbloom", "Telara Dawnfern",
  "Thalwen Deepbloom", "Thiriel Nightglen", "Thyrenna Glowleaf", "Tinuiel Mistveil", "Tinúviel Softwhisper",
  "Tiriel Flameveil", "Tirwen Fernsong", "Tyael Lightstream", "Vaelwen Dreamshade", "Valariel Starbloom",
  "Velwen Silverfern", "Virelya Moonleaf", "Yavanna Sunshade", "Ylithra Dreammist", "Ysolde Rainfeather",
  "Zariel Nightshade", "Ziniel Emberleaf", "Zylaria Glowbloom"
      
    ]
  },
  Demônios: {
    male: [
      "Abaddon Blackflame",
  "Aamon Dreadspire",
  "Abyzou Vilefang",
  "Acheron Nightmaw",
  "Adramalech Ironwrath",
  "Agares Bloodvein",
  "Ahriman Shadowrage",
  "Alastor Doomheart",
  "Alloces Darkthorn",
  "Amdusias Hellgrove",
  "Amy Deathgaze",
  "Andras Cruelfang",
  "Andrealphus Sinshade",
  "Andromalius Voidborn",
  "Asmodeus Blightmark",
  "Astaroth Bonewhisper",
  "Azazel Soulrender",
  "Bael Rotfang",
  "Baalberith Flamevein",
  "Balam Skullpierce",
  "Barbas Hexwrought",
  "Barbatos Gravetide",
  "Bathin Nightscar",
  "Beelzebub Filthgrin",
  "Behemoth Warbringer",
  "Belial Stonecurse",
  "Berith Gloomveil",
  "Bifrons Wyrmfire",
  "Botis Thornblood",
  "Buer Plaguegaze",
  "Bune Ashfang",
  "Caim Doomvein",
  "Cimeries Howlshade",
  "Crocell Burnscar",
  "Dantalion Mireclaw",
  "Decarabia Blackvenom",
  "Eligos Ashenmark",
  "Flauros Smokespine",
  "Focalor Brimveil",
  "Foras Hellgrin",
  "Forneus Nightwrath",
  "Furcas Grimsong",
  "Furfur Scourgeborn",
  "Gaap Ironhowl",
  "Gemory Deathbloom",
  "Glasya Cruelthorn",
  "Gusion Bloodmark",
  "Halphas Warshard",
  "Haures Scorchbrand",
  "Ipos Nightbane",
  "Leraje Blistershade",
  "Malphas Doomscar",
  "Marbas Soulmaw",
  "Marchosias Wargrin",
  "Murmur Gravescorn",
  "Naberius Dreadgrip",
  "Orabas Blackhowl",
  "Orias Stormwrath",
  "Orobas Grimeveil",
  "Paimon Sinhowl",
  "Phenex Burntwing",
  "Purson Deathveil",
  "Raum Skullveil",
  "Ronove Hexblade",
  "Sabnock Gorefang",
  "Saleos Shardflame",
  "Sallos Venomheart",
  "Seere Fireblight",
  "Sitri Thornvein",
  "Stolas Ashwhisper",
  "Sytry Blackvein",
  "Valac Duskgore",
  "Valefar Plaguehorn",
  "Vapula Rotbrand",
  "Vassago Dreadshade",
  "Vepar Tidescourge",
  "Zagan Vilebrand",
  "Zepar Woundtongue",
  "Ziminiar Gravedancer",
  "Orthon Slagblood",
  "Rahovart Mirethorn",
  "Lucifer Mourntide",
  "Mephistopheles Nightcurse",
  "Samael Flamegrip",
  "Mammon Ironmaw",
  "Belphegor Grimefang",
  "Aamon Vilefang",
  "Abaddon Duskgore",
  "Abaddon Filthgrin",
  "Abaddon Fireblight",
  "Abaddon Grimefang",
  "Acheron Brimveil",
  "Acheron Stormwrath",
  "Acheron Venomheart",
  "Adramalech Flamegrip",
  "Adramalech Scourgeborn",
  "Adramalech Skullpierce",
  "Adramalech Warshard",
  "Agares Blightmark",
  "Agares Blistershade",
  "Agares Plaguehorn",
  "Agares Sinshade",
  "Agares Vilebrand",
  "Ahriman Doomheart",
  "Ahriman Duskgore",
  "Ahriman Ironmaw",
  "Ahriman Thornblood",
  "Alastor Deathveil",
  "Alastor Doomscar",
  "Alloces Blackflame",
  "Alloces Bloodmark",
  "Alloces Dreadshade",
  "Alloces Gravescorn",
  "Alloces Grimsong",
  "Alloces Plaguehorn",
  "Amdusias Burnscar",
  "Amdusias Thornvein",
  "Amy Burnscar",
  "Amy Plaguegaze",
  "Andras Ashwhisper",
  "Andras Bloodvein",
  "Andras Deathveil",
  "Andras Grimeveil",
  "Andras Nightbane",
  "Andras Nightmaw",
  "Andrealphus Blackflame",
  "Andrealphus Rotbrand",
  "Andrealphus Thornblood",
  "Andrealphus Warbringer",
  "Andrealphus Woundtongue",
  "Andromalius Flamevein",
  "Andromalius Hexblade",
  "Andromalius Skullpierce",
  "Asmodeus Bloodmark",
  "Asmodeus Burntwing",
  "Asmodeus Cruelthorn",
  "Asmodeus Gravetide",
  "Asmodeus Sinhowl",
  "Asmodeus Sinshade",
  "Asmodeus Thornblood",
  "Asmodeus Thornvein",
  "Asmodeus Tidescourge",
  "Asmodeus Warshard",
  "Astaroth Dreadshade",
  "Astaroth Gorefang",
  "Astaroth Nightbane",
  "Astaroth Nightcurse",
  "Azazel Dreadgrip",
  "Azazel Gloomveil",
  "Azazel Mireclaw",
  "Azazel Skullveil",
  "Azazel Stormwrath",
  "Azazel Thornblood",
  "Azazel Thornvein",
  "Azazel Vilebrand",
  "Baalberith Deathgaze",
  "Baalberith Mireclaw",
  "Baalberith Scourgeborn",
  "Baalberith Skullveil",
  "Bael Nightbane",
  "Bael Smokespine",
  "Bael Stonecurse",
  "Bael Tidescourge",
  "Bael Voidborn",
  "Balam Blistershade",
  "Balam Burntwing",
  "Balam Doomheart",
  "Balam Doomscar",
  "Balam Filthgrin",
  "Balam Grimeveil",
  "Balam Hexwrought",
  "Balam Nightbane",
  "Balam Nightwrath",
  "Barbas Soulmaw",
  "Barbas Voidborn",
  "Barbatos Dreadshade",
  "Barbatos Grimeveil",
  "Barbatos Nightwrath",
  "Barbatos Skullpierce",
  "Barbatos Soulmaw",
  "Barbatos Woundtongue",
  "Bathin Brimveil",
  "Bathin Burnscar",
  "Bathin Dreadshade",
  "Bathin Filthgrin",
  "Bathin Hellgrove",
  "Bathin Ironhowl",
  "Bathin Sinshade",
  "Bathin Smokespine",
  "Beelzebub Darkthorn",
  "Beelzebub Deathgaze",
  "Beelzebub Nightmaw",
  "Beelzebub Wargrin",
  "Behemoth Blightmark",
  "Behemoth Gravetide",
  "Behemoth Scorchbrand",
  "Behemoth Woundtongue",
  "Belial Bloodvein",
  "Belial Cruelfang",
  "Belial Dreadgrip",
  "Belial Gravedancer",
  "Belial Grimefang",
  "Belial Nightmaw",
  "Belial Plaguehorn",
  "Belial Smokespine",
  "Belphegor Ashwhisper",
  "Belphegor Blistershade",
  "Belphegor Mourntide",
  "Belphegor Skullpierce",
  "Belphegor Soulrender",
  "Berith Blistershade",
  "Berith Deathbloom",
  "Berith Gravescorn",
  "Berith Grimeveil",
  "Berith Hellgrove",
  "Berith Ironmaw",
  "Berith Scorchbrand",
  "Bifrons Scourgeborn",
  "Bifrons Warbringer",
  "Bifrons Wargrin",
  "Botis Blackhowl",
  "Botis Brimveil",
  "Botis Doomvein",
  "Botis Dreadgrip",
  "Buer Blackhowl",
  "Buer Deathbloom",
  "Buer Dreadgrip",
  "Buer Vilebrand",
  "Bune Brimveil",
  "Bune Deathgaze",
  "Bune Gravescorn",
  "Caim Duskgore",
  "Caim Flamegrip",
  "Caim Slagblood",
  "Cimeries Cruelfang",
  "Cimeries Cruelthorn",
  "Cimeries Grimefang",
  "Cimeries Hellgrin",
  "Cimeries Nightmaw",
  "Cimeries Skullpierce",
  "Cimeries Soulmaw",
  "Cimeries Venomheart",
  "Crocell Blackflame",
  "Crocell Gorefang",
  "Crocell Gravetide",
  "Crocell Hellgrove",
  "Crocell Smokespine",
  "Crocell Vilebrand",
  "Dantalion Gravescorn",
  "Dantalion Smokespine",
  "Decarabia Blackvenom",
  "Decarabia Deathgaze",
  "Decarabia Dreadshade",
  "Decarabia Gravedancer",
  "Decarabia Gravetide",
  "Decarabia Mourntide",
  "Decarabia Rotfang",
  "Decarabia Smokespine",
  "Eligos Gloomveil",
  "Eligos Howlshade",
  "Eligos Nightwrath",
  "Eligos Stonecurse",
  "Eligos Venomheart",
  "Eligos Vilebrand",
  "Flauros Cruelfang",
  "Flauros Filthgrin",
  "Flauros Hexblade",
  "Flauros Scourgeborn",
  "Flauros Stormwrath",
  "Flauros Woundtongue",
  "Focalor Cruelthorn",
  "Focalor Deathveil",
  "Focalor Grimsong",
  "Focalor Rotfang",
  "Focalor Skullveil",
  "Focalor Vilefang",
  "Focalor Warbringer",
  "Foras Fireblight",
  "Foras Flamegrip",
  "Foras Gloomveil",
  "Foras Hellgrove",
  "Foras Shadowrage",
  "Foras Soulmaw",
  "Forneus Ashwhisper",
  "Forneus Darkthorn",
  "Forneus Ironhowl",
  "Forneus Rotfang",
  "Forneus Smokespine",
  "Furcas Cruelfang",
  "Furcas Deathbloom",
  "Furcas Flamevein",
  "Furcas Slagblood",
  "Furfur Deathgaze",
  "Furfur Hexblade",
  "Furfur Scourgeborn",
  "Furfur Wyrmfire",
  "Gaap Doomheart",
  "Gaap Gloomveil",
  "Gaap Hexblade",
  "Gaap Howlshade",
  "Gaap Mourntide",
  "Gaap Nightscar",
  "Gaap Plaguegaze",
  "Gaap Thornblood",
  "Gemory Ironwrath",
  "Gemory Mirethorn",
  "Glasya Hexblade",
  "Gusion Ashwhisper",
  "Gusion Blightmark",
  "Gusion Bloodvein",
  "Gusion Brimveil",
  "Gusion Deathgaze",
  "Gusion Nightmaw",
  "Gusion Plaguegaze",
  "Gusion Shadowrage",
  "Gusion Stonecurse",
  "Gusion Vilefang",
  "Halphas Blackvenom",
  "Halphas Bloodvein",
  "Halphas Bonewhisper",
  "Halphas Dreadspire",
  "Halphas Vilebrand",
  "Haures Deathbloom",
  "Haures Dreadspire",
  "Haures Mourntide",
  "Haures Thornvein",
  "Ipos Blightmark",
  "Ipos Gravescorn",
  "Ipos Hexblade",
  "Ipos Shadowrage",
  "Ipos Voidborn",
  "Ipos Warshard",
  "Leraje Doomscar",
  "Leraje Dreadspire",
  "Leraje Stormwrath",
  "Lucifer Howlshade",
  "Lucifer Mireclaw",
  "Lucifer Rotfang",
  "Lucifer Scourgeborn",
  "Lucifer Sinshade",
  "Malphas Gravetide",
  "Malphas Hellgrove",
  "Malphas Sinshade",
  "Malphas Stormwrath",
  "Mammon Flamegrip",
  "Mammon Ironhowl",
  "Mammon Plaguehorn",
  "Marbas Blackvein",
  "Marbas Burntwing",
  "Marbas Filthgrin",
  "Marbas Gloomveil",
  "Marbas Grimsong",
  "Marbas Mireclaw",
  "Marchosias Bloodvein",
  "Marchosias Cruelthorn",
  "Marchosias Grimefang",
  "Marchosias Scorchbrand",
  "Marchosias Venomheart",
  "Marchosias Vilefang",
  "Mephistopheles Ashenmark",
  "Mephistopheles Bloodmark",
  "Mephistopheles Bonewhisper",
  "Mephistopheles Deathveil",
  "Mephistopheles Doomheart",
  "Mephistopheles Gravetide",
  "Mephistopheles Grimeveil",
  "Mephistopheles Ironwrath",
  "Mephistopheles Mourntide",
  "Mephistopheles Soulmaw",
  "Murmur Cruelthorn",
  "Murmur Doomheart",
  "Murmur Dreadshade",
  "Murmur Grimeveil",
  "Murmur Mireclaw",
  "Murmur Vilebrand",
  "Naberius Blistershade",
  "Naberius Brimveil",
  "Naberius Deathgaze",
  "Naberius Woundtongue",
  "Orabas Blackvenom",
  "Orabas Grimsong",
  "Orabas Woundtongue",
  "Orias Blackhowl",
  "Orias Brimveil",
  "Orias Cruelfang",
  "Orias Nightbane",
  "Orias Plaguehorn",
  "Orias Stormwrath",
  "Orias Tidescourge",
  "Orobas Hexwrought",
  "Orobas Ironhowl",
  "Orobas Soulmaw",
  "Orobas Wargrin",
  "Orthon Shadowrage",
  "Paimon Blackhowl",
  "Paimon Ironmaw",
  "Paimon Wargrin",
  "Phenex Blackvein",
  "Phenex Bloodvein",
  "Phenex Deathbloom",
  "Phenex Deathveil",
  "Phenex Dreadspire",
  "Phenex Stonecurse",
  "Phenex Venomheart",
  "Purson Blackflame",
  "Purson Blightmark",
  "Purson Bloodmark",
  "Purson Doomheart",
  "Purson Grimefang",
  "Purson Plaguegaze",
  "Rahovart Cruelthorn",
  "Rahovart Duskgore",
  "Rahovart Shadowrage",
  "Rahovart Tidescourge",
  "Rahovart Vilefang",
  "Rahovart Wargrin",
  "Raum Blackvein",
  "Raum Bonewhisper",
  "Raum Brimveil",
  "Raum Gorefang",
  "Raum Ironmaw",
  "Ronove Gloomveil",
  "Ronove Hexwrought",
  "Sabnock Darkthorn",
  "Sabnock Filthgrin",
  "Sabnock Gravetide",
  "Saleos Burntwing",
  "Saleos Ironhowl",
  "Saleos Vilefang",
  "Sallos Nightcurse",
  "Sallos Sinhowl",
  "Samael Grimeveil",
  "Samael Rotfang",
  "Samael Stormwrath",
  "Seere Doomvein",
  "Seere Duskgore",
  "Seere Gravedancer",
  "Seere Skullpierce",
  "Seere Skullveil",
  "Seere Voidborn",
  "Seere Warbringer",
  "Sitri Stormwrath",
  "Sitri Vilebrand",
  "Stolas Blackvein",
  "Stolas Rotbrand",
  "Stolas Smokespine",
  "Stolas Warbringer",
  "Sytry Blackvenom",
  "Sytry Mirethorn",
  "Sytry Woundtongue",
  "Valac Brimveil",
  "Valac Dreadgrip",
  "Valac Grimsong",
  "Valac Warshard",
  "Valefar Ashfang",
  "Valefar Blackflame",
  "Valefar Doomvein",
  "Valefar Duskgore",
  "Valefar Ironwrath",
  "Valefar Nightwrath",
  "Valefar Rotfang",
  "Vapula Ashenmark",
  "Vapula Duskgore",
  "Vapula Filthgrin",
  "Vapula Slagblood",
  "Vapula Soulrender",
  "Vapula Vilefang",
  "Vassago Brimveil",
  "Vassago Cruelfang",
  "Vassago Deathgaze",
  "Vassago Doomscar",
  "Vassago Warshard",
  "Vepar Dreadgrip",
  "Vepar Warshard",
  "Zagan Flamevein",
  "Zagan Hellgrin",
  "Zagan Sinshade",
  "Zagan Skullveil",
  "Zagan Vilebrand",
  "Zagan Warbringer",
  "Zepar Nightscar",
  "Ziminiar Ashenmark",
  "Ziminiar Blackvenom",
  "Ziminiar Dreadshade",
  "Ziminiar Gravescorn",
  "Ziminiar Scourgeborn",
      
    ],
    female: [
       "Lilith Vexara", "Morwen Drazhal", "Zyra Nocthyl", "Sabbatha Kreel", "Ashera Malgrith",
  "Nyx Velkara", "Damara Theryss", "Seraphine Vornyx", "Velira Duskryn", "Isolde Marzeth",
  "Thalissa Nyrr", "Nerathys Vorne", "Lyssandra Kelreth", "Azelith Sorrowen", "Yzara Hellvain",
  "Karynth Drelza", "Vireth Morgasha", "Zelara Karnyx", "Lilura Graeven", "Mazrika Valshar",
  "Erisyth Shadeborn", "Thyra Zarneth", "Xezra Vilkran", "Selkara Draeve", "Maevira Kalthys",
  "Zavira Nullwyn", "Drusala Venmyr", "Ravika Morwyn", "Zynthis Drelkha", "Olivra Mournshade",
  "Maldrith Xevara", "Ylvanna Graeven", "Kelithra Zarhyn", "Zalara Drevin", "Virelya Nyxthra",
  "Morgala Therzin", "Azelyra Mavren", "Kireth Volsha", "Ysara Drelna", "Nemezia Kravyn",
  "Thyssira Velzhun", "Xanthera Gloomveil", "Lyzeth Kratha", "Varishka Drelmor", "Sybelle Kharza",
  "Velzara Netheris", "Shadira Varnyx", "Myzara Kelverin", "Zaralyn Morentha", "Sarethys Vileth",
  "Zorya Vesperyn", "Drazhara Kelthys", "Iridra Varneth", "Xelira Thazryn", "Vyxaria Mordaz",
  "Melyra Voidwynn", "Abyssia Zarenth", "Calvera Nocthra", "Thyrene Kalthora", "Morvella Zalrith",
  "Zekaria Dusklyn", "Sylzara Helkra", "Nymeria Vorlyn", "Thazira Kreelith", "Khalyra Drelsha",
  "Nerezza Shadreth", "Sinthara Malvera", "Zaphyra Darkveil", "Lilix Morgana", "Sazhra Voidlyn",
  "Azmara Thoryss", "Velmira Krezzeth", "Myrelka Zariel", "Yzalia Mournshard", "Zanika Draveth",
  "Zafrina Vyrren", "Thorynza Graemira", "Vyshara Doomveil", "Zelvera Malshae", "Morrith Vylneth",
  "Naelira Thazgrim", "Selzira Vexelyn", "Ashkara Morzenth", "Kravella Velnar", "Sylvara Krueth",
  "Yzzeth Malrith", "Velshara Nyrryn", "Zarmina Halvek", "Dravika Sorneth", "Kalmyra Duskveil",
  "Orvella Noctira", "Tazmira Graelith", "Xazhara Vryneth", "Zylla Mournvael", "Thalira Gloometh",
  "Kezhara Velgrim", "Ravelyth Durneth", "Malgora Xerenth", "Selshira Valkra", "Niraya Hellsyn",
  "Mazryth Drelneth", "Zaphara Voidraz", "Thylissa Grimwen", "Lilveth Morgryn", "Karnessa Shadzar",
  "Zezria Nightbloom", "Ysvelda Thornax", "Vyrethra Kalthor", "Skarza Draklyn", "Kharissa Malnyx","Selgryn Azethor",
  "Yzavorne Nyxshar",
  "Liltha Yzzeth",
  "Kharith Morlyn",
  "Karza Zorveil",
  "Sazsha Xazlyn",
  "Velkra Khaenth",
  "Sazkra Isoeth",
  "Kalzarhyn Lysren",
  "Kireth Velsha",
  "Vyxnyx Sinneth",
  "Virraz Drazarhyn",
  "Kelmor Xazveil",
  "Xazshar Myrnyrr",
  "Zoreth Melgrim",
  "Zavvara Xazrith",
  "Selvin Sazsha",
  "Kirven Zeketh",
  "Nymnyx Xazenth",
  "Mornax Ravkra",
  "Mazthor Zapnax",
  "Thawen Lilxeth",
  "Lyztha Xelren",
  "Sinrren Zankran",
  "Zapkara Ylvana",
  "Vyxryn Myzbloom",
  "Naekha Zezxeth",
  "Lilsha Mazthys",
  "Lillyn Ysarith",
  "Velneth Zansha",
  "Thaeth Velmor",
  "Yzaenth Karza",
  "Khaeth Vysriel",
  "Maeana Zylveth",
  "Veleth Zaryn",
  "Mallyn Moraz",
  "Yzarren Zapborn",
  "Kragrim Drashar",
  "Calvyn Nirlith",
  "Melzhun Vyreth",
  "Lilsha Zalnyx",
  "Kraren Velara",
  "Ravsha Naeza",
  "Zarneth Lyzss",
  "Zarneth Yzarren",
  "Zellyn Isorim",
  "Lilira Lilveth",
  "Azmveth Nerreth",
  "Thaara Xansha",
  "Kargryn Mazra",
  "Sertha Zelveil",
  "Nyxriel Velveth",
  "Zynvorne Naeveil",
  "Zynax Malnax",
  "Zarenth Selshar",
  "Xazriel Nembloom",
  "Nernyx Sablyn",
  "Serrith Ysvaz",
  "Myzreth Thymor",
  "Xaznyx Morhra",
  "Saznyx Drazar",
  "Xelveth Kelneth",
  "Tazvael Vyrmarzeth",
  "Orvkra Nerlyn",
  "Varwynn Lilveil",
  "Sylnyx Thyza",
  "Morenth Zylwynn",
  "Varkra Lileve",
  "Azeven Velvin",
  "Drashar Tazveil",
  "Zekenth Varra",
  "Ysaneth Draveil",
  "Lillyn Naevara",
  "Morvain Ysalyn",
  "Morsha Zarae",
  "Khathys Zapgrith",
  "Ysanax Zaferyss",
  "Erishard Thytha",
  "Sylshar Zalvael",
  "Maznyx Yzasha",
  "Zarthor Xanvek",
  "Krawyn Velaz",
  "Draveil Erikreel",
  "Lysneth Azmriel",
  "Serzeth Thokara",
  "Lilira Olinyx",
  "Maenyx Zaris",
  "Xelthys Zapkha",
  "Tazthys Drakra",
  "Morthra Vyrkra",
  "Sylveil Kirsha",
  "Khaven Erineth",
  "Erirren Myzsha",
  "Ylvgrim Tharyn",
  "Sabthys Vyskha",
  "Zaveve Zelrith",
  "Ysvmira Zekvorne",
  "Zorbloom Zelnyx",
  "Serana Azewynn",
  "Zapneth Azmren",
  "Drakran Thyrren",
  "Erikran Kireth",
  "Malaz Kezenth",
  "Abyzin Zafthys",
  "Xezza Tazsha",
  "Mornyrr Thaneth",
  "Ravneth Thagryn",
  "Abyra Isora",
  "Kelhra Zynthys",
  "Moreth Zafsha",
  "Thygrim Sergrim",
  "Orveryss Sybnax",
  "Ysathys Zeltha",
  "Zafneth Khazeth",
  "Zapvin Sarvyn",
  "Thywyn Zareth",
  "Ravneth Velvorne",
  "Thalyn Velvain",
  "Ashryn Syllith",
  "Zekmyr Yzaveil",
  "Sarneth Khaara",
  "Khashar Thazeth",
  "Tazthor Ylvveil",
  "Zelna Morveil",
  "Zelveil Kaleve",
  "Isomarzeth Virryn",
  "Thyira Khamira",
  "Nerkra Ylvsha",
  "Zelmor Zylhra",
  "Zafmor Malryn",
  "Ysara Myzkran",
  "Azetha Sybrren",
  "Serkra Selsha",
  "Zavkra Selven",
  "Zapryn Nerbloom",
  "Velvorne Selveil",
  "Varwynn Ysaven",
  "Thyyn Nereth",
  "Zarlyn Sarveil",
  "Nereth Malveil",
  "Zezlyn Syllyn",
  "Selraz Thywen",
  "Zargrim Druveil",
  "Ysvyn Yzzneth",
  "Zalraz Azmwen",
  "Drunyx Lyzneth",
  "Melmarzeth Lilsha",
  "Oliyn Nerveil",
  "Morvara Karsha",
  "Seleth Iritha",
  "Maewynn Thygryn",
  "Zanriel Azeveil",
  "Zorveil Virryn",
  "Eriven Thykara",
  "Morneth Azevain",
  "Kezae Vyrgrith",
  "Xezthys Malzhun",
  "Sabnyx Lysxeth",
  "Ravshade Yzaza",
  "Azeeth Khalyn",
  "Azerren Sargryn",
  "Karwynn Tazsha",
  "Sazxeth Maewen",
  "Ashlyn Lilryn",
  "Vargrim Sybveil",
  "Thythra Kezkara",
  "Myrthra Lilvorne",
  "Vyrsyn Thynyx",
  "Sazyn Sabmyr",
  "Velenth Shaae",
  "Zaptha Morshard",
  "Zorven Virryn",
  "Yzathor Morxeth",
  "Oliveth Lilnyx",
  "Shaza Olimira",
  "Yzalyn Zarvin",
  "Shaneth Zargrim",
  "Zoreve Ysvsha",
  "Sarshade Xazeve",
  "Erishade Ylvveil",
  "Morkra Nemvin",
  "Mormor Shayn",
  "Xezlyn Ashaz",
  "Azmrith Skasha",
  "Karlyn Zapveil",
  "Nemryn Ysvraz",
  "Kareve Tholyn",
  "Isolyn Orvgrim",
  "Vyxnax Zygrim",
  "Yzatha Yzzmarzeth",
  "Skayn Morgrim",
  "Thyae Morveil",
  "Irinyx Tholyn",
  "Kalthra Zylthys",
  "Kravin Ashgryn",
  "Skaaz Ashae",
  "Thyvin Lyseth",
  "Serwyn Ashveth",
  "Naekra Zarkran",
  "Lilthor Thaenth",
  "Azmeth Kalwyn",
  "Kirvara Velza",
  "Kezveil Velss",
  "Isovael Zarkreel",
  "Lyssha Olilyn",
  "Vyxthys Zorsha",
  "Ashis Ravnyx",
  "Nemsha Lilzhun",
  "Malvain Khaveil",
  "Kalkra Xeznyx",
  "Naegrith Olivyn",
  "Nerkra Xelxeth",
  "Ashveth Khalyn",
  "Nemlyn Zynkreel",
  "Thamira Xannax",
  "Xanveil Zelmarzeth",
  "Sarae Selaz",
  "Zoreve Selveil",
  "Lyzxeth Drawynn",
  "Lilsha Morvorne",
  "Nerwen Nerborn",
  "Thaenth Nymmira",
  "Azebloom Karmarzeth",
  "Taztha Nernyx",
  "Kezwyn Sereryss",
  "Zormarzeth Tazeve",
  "Vyxvain Olizar",
  "Ravveil Zarbloom",
  "Zavlyn Thanyrr",
  "Ysaryn Ysaven",
  "Yzzzin Sylsha",
  "Nyxkran Irieth",
  "Sylra Lilthra",
  "Nirwen Lilana",
  "Lilae Morryn",
  "Yzavek Vyrshard",
  "Yzzzhun Kelza",
  "Ashra Velsha",
  "Sazgrith Taznax",
  "Moraz Tazvin",
  "Krakara Thaenth",
  "Sylkra Abyshade",
  "Zafneth Moryn",
  "Xezveil Zelmira",
  "Kirgrim Lilveil",
  "Draeth Calgryn",
  "Velvorne Zelwen",
  "Yzaveil Azenyx",
  "Azeven Zyveil",
  "Lilborn Malvyn",
  "Skamyr Zelveil",
  "Calza Mornyrr",
  "Thyneth Thyshard",
  "Zanveil Sylmira",
  "Morren Nereryss",
  "Xankara Maesha",
  "Maelyn Zelveil",
  "Vyxra Sazenth",
  "Nyxshar Velkran",
  "Isoaz Vellyn",
  "Sarbloom Naeeryss",
  "Thalyn Nyxwynn",
  "Ashgryn Zarza",
  "Xannyx Velneth",
  "Zezgryn Ysveryss",
  "Zynsha Zapna",
  "Azmsha Nemxeth",
  "Xezlyn Nymwyn",
  "Zavsha Maevain",
  "Mazenth Varenth",
  "Thatha Lilss",
  "Velthys Dragrim",
  "Zarra Thyriel",
  "Mazna Lyzeve",
  "Karkra Ysvrim",
  "Kezmor Zeznyx",
  "Zafkra Zapss",
  "Zarnyx Thatha",
  "Lyshra Virryn",
  "Ysvlyn Erieth",
  "Lilsha Nyxlith",
  "Kiryn Kezwen",
  "Morveil Khathor",
  "Nyxthys Myzvek",
  "Velvek Velvyn",
  "Orvneth Isoveil",
  "Yzais Ashzar",
  "Sarra Zafzeth",
  "Thyeth Khaveil",
  "Isois Eriis",
  "Drunyx Selrim",
  "Sabveil Selenth",
  "Morss Lilthys",
  "Zorza Zafmor",
  "Zarven Morwen",
  "Kelneth Morthor",
  "Karthys Morlyn",
  "Mazshar Nymvorne",
  "Xellyn Zylwen",
  "Kirzin Morgrim",
  "Erizhun Lysvara",
  "Azmryn Zapwynn",
  "Selsha Kalven",
  "Damkha Karnax",
  "Varthys Lilwynn",
  "Orvis Thykha",
  "Zaptha Kalza",
  "Virvyn Ysaneth",
  "Sertha Selkara",
  "Zalshard Ravthys",
  "Calmarzeth Sazriel",
  "Zezkara Zarvael",
  "Morshade Nirren",
  "Velveil Damneth",
  "Kalmira Zekgrith",
  "Skarith Thagrim",
  "Nemlyn Selana",
  "Lilveil Nirxeth",
  "Draeth Virriel",
  "Vyxnyx Melnax",
  "Karzeth Morrren",
  "Shashar Ylvlyn",
  "Selkha Sinriel",
  "Keznyrr Velna",
  "Zafbloom Raventh",
  "Tazshard Myzzin",
  "Velryn Zylmira",
  "Zafra Sazven",
  "Khasha Isoeryss",
  "Velveil Velthra",
  "Thyshard Nirzeth",
  "Mallyn Morkra",
  "Zylith Karra",
  "Zywynn Zynryn",
  "Thavorne Thywyn",
  "Zynzhun Mazmor",
  "Azmwyn Draveth",
  "Ravra Yzzmor",
  "Zezshade Sarlyn",
  "Calven Vyswyn",
  "Varara Nerwynn",
  "Virmira Drawyn",
  "Sabira Taztha",
  "Malborn Krasha",
  "Varshar Ravveth",
  "Drukara Selshar",
  "Kareth Nertha",
  "Mazbloom Serlyn",
  "Nemshade Shamarzeth",
  "Khatha Sazrren",
  "Ashyn Mazvyn",
  "Selnyrr Damzar",
  "Nerthra Yzaneth",
  "Xezkara Zanwyn",
  "Sereve Azerith",
  "Moreve Zafkran",
  "Zapkra Sellyn",
  "Velvael Zarnax",
  "Thalyn Varenth",
  "Zapven Khavyn",
  "Thashade Zeznyx",
  "Sarzeth Yzavyn",
  "Krahra Karvorne",
  "Naezarhyn Ysvborn",
  "Zanira Shaneth",
  "Xanmor Xezgrim",
  "Damwen Skavyn",
  "Yzzsyn Eriwyn",
  "Tazryn Tazeth",
  "Thakha Xezaz",
  "Sylneth Zarnyx",
  "Mellith Vellith",
  "Krais Yzana",
  "Azenyx Lilreth",
  "Velzarhyn Kalmira",
  "Morkran Sargrith",
  "Ysaneth Azenyx",
  "Vireth Sinlyn",
  "Sazzarhyn Selrim",
  "Karnax Nyxsha",
  "Ashthra Vyrlyn",
  "Shasha Thalyn",
  "Zalveil Thavael",
  "Sybsyn Kezwynn",
  "Kelveil Zezshade",
  "Thyenth Karrren",
  "Xazaz Lileth",
  "Mornyrr Olieth",
  "Drathys Lilrim",
  "Sybthys Azelyn",
  "Myrneth Vireth",
  "Ravhra Nirvain",
  "Kelveil Sybren",
  "Nymmor Thyvyn",
  "Kirven Ysazarhyn",
  "Tazgryn Velneth",
  "Thyraz Ysaryn",
  "Ashtha Sylryn",
  "Maelyn Thythys",
  "Mallyn Thykra",
    ]
  },
    "model": {
    male: [
      
    ],
    female: [
      
    ]
  },
};
